### ISSUE TITLE
越简单越不简单

### ISSUE THREAD

**Issue by zkk717** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#100]
## 做，是最好的学
一直很喜欢**半撇**说的这句话，当初就是因为看到了这句话所以毫不犹豫的再 [网易云课堂](http://study.163.com/) 上买下了 *微信公众号高级排版* 的课程。很喜欢 [半撇私塾](www.bpteach.com) 
  的整体感觉，可以感觉到课程做的很用心，分享的是满满的干货。

从买课到现在半个多月了，忙到现在才来写这个，好喜欢 **Markdown** 的抒写风格，这几个特征让人感觉写作就是一种享受：
* 流畅
* 自然
* 简单 

最后感谢 [半撇私塾](www.bpteach.com) 提供给我们这么好的学习机会，也感谢各位小伙伴们的互相鼓励和支持

**Comment by fang-yu** [comment]
Hi，练习场的作业需要在对应的issue跟帖回复，我先关闭这一条issue哈。
