### ISSUE TITLE
【微专业第三期】小班级报到：找到你的学伴

### ISSUE THREAD

**Issue by YeziGZ** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#102]
## 什么是「小班级」

哈佛耶鲁、牛津剑桥等名校，给人最大的财富是在校期间的同辈压力与可以托付后背的同辈信任。随着人类知识的日益爆炸，我们不仅仅在青春期荷尔蒙旺盛的时候，需要同辈压力刺激。毕业后也一直需要一个能刺激自己发展的同辈压力环境。

我们坚信：同辈压力是最好的学习动力。见到别人那么努力，你不好意思堕落。所以在半撇私塾的学习中，我们也同样强调「同伴学习」。

>「同伴学习」是7个人所组成的小班级，可以是一个高效运作的团队，可以是相互帮助、并肩作战的学习挚友。7人成班，凝结一心。

所以在课程启动的开始，你们需要找到你们的「小班级」。

## 如何完成开学「小班级」任务

在开学第一周启动周中，需要「小班班长」在此Issue完成以下班级展示：

- 班级信息
  - 班级编号
  - 班级名称
  - 班级口号
  - 班级logo

- 班级成员风采
  - 成员组成信息：真实姓名+昵称＋担任哪个科目的课代表＋来自哪里＋职业＋一句话介绍
  - [可选]班级风采展示／班级第一次线上／线下见面活动

> 如果有机会，大家第一次见面可以采用线上或者线下的方式。

## 更多展示

当然，以小班的名义，你可以在这里发布：

- 小班成员的风采展示；
- 小班线上活动的精彩感言、总结；
- 小班线下活动的精彩照片、活动总结等；
- 小班的学习情况分享；
- 一切你觉得可以呈现出小班特色的内容。

### 更多帮助

1. [《微专业小班级管理指导手册》](https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/wiki/%E5%BE%AE%E4%B8%93%E4%B8%9A%E5%B0%8F%E7%8F%AD%E7%BA%A7%E7%AE%A1%E7%90%86%E6%8C%87%E5%AF%BC%E6%89%8B%E5%86%8C)
2. 想要认识往期班级？请点击查看
[「全栈新媒体运营」微专业第一期班级风采展示](https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/22)
[「全栈新媒体运营」微专业第二期班级风采展示](https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/84)

**Comment by fang-yu** [comment]
举个例子

### 班级

- 编号：000
- 班级名称：东东枪小班
- 班级口号：做是最好的学。
- 班级logo：

含义：编号000，形状化成三个o，互相连接，凝聚在一起，象征着东东枪小班团结一致；三个o分别代表三个字母

  - Our：我们班级所有人；
  - Output：输出／做是最好的学；
  - Outstanding：每个人班级成员都是优秀、突出的小伙伴；

![](http://obfe8r4sl.bkt.clouddn.com/logo2.png)

### 班级成员风采

#### 成员名单（名字可用真实姓名或昵称）

- 刘念，应用传播学课代表，来自北京，体制内，逗比开朗；
- 陈欢，故事结构课代表；来自武汉，大四学生，清奇脑洞少女；
- 乌拉，新媒体产品定位课代表，来自广州，产品经理，不爱美食的产品经理不是优秀网络主播；
- S小姐，新媒体创意写作课代表，来自广州，大四学生，能写会逗新闻咖；
- ......

#### 成员风采展

![](https://ww2.sinaimg.cn/large/006tKfTcgw1fbja6lxxh4j30qo0f0q4w.jpg)

#### 第一次会议

2017年6月11日，东东枪小班进行了初次见面，虽然有两位小伙伴在广州之外的城市，但并不能阻挡我们小班成员间的热情。这一次的线上见面，大家一见如故，仿佛回到了学生时代。

![图片来源于网站](http://obfe8r4sl.bkt.clouddn.com/timg.jpeg)

**Comment by TangHaoXuan** [comment]
# **班级信息**
- **班级编号：001**
- **班级名称：新媒体一班**
- **班级口号：勇于拼搏，超越自我**
# 班级LOGO
![1](https://user-images.githubusercontent.com/34592370/34079796-d8229204-e36f-11e7-9777-0fba065e248f.jpg)

### **含义：新媒体一班，勇于拼搏超越自我，口号在LOGO当中体现，电脑代表新媒体行业，从显示屏里面飞出来的是各种资源，代表着我们在这半撇私塾学习新媒体和其中的资源，新时代新媒体新知识的意思。**

## 成员名单
姓名 | 来自 | 职业 | 课代表 | 自我介绍
-- | -- | -- | -- | --
唐颢轩 | 北京 | 设计专员 | 班长 | 成功就是简单的事情不断地重复做。
姚凯 | 北京 | 电商总监 | 新媒体营销理论与实战 | 大家好我是一个爱学习爱生活爱健身的小学生？
曾成海 | 北京 | 市场运营 | 新媒体终极排版 | 付出不亚于任何人的努力，成为自己想要成为的人！
杨广辉 | 北京 | 市场运营 | 新媒体产品设计 | stay hangry，stay foolish!
许浩喆 | 大连 | 软件项目经理 | 新媒体应用传播学 | 能实现金融it，英语，日语相关需求。
李昱 | 北京 | 新媒体文案 | 新媒体创意写作 | 一个爱好文字的人，希望在文字方面有所建树。

## 成员风采
![default](https://user-images.githubusercontent.com/34592370/34079801-e0125e04-e36f-11e7-8240-3a0210550101.jpg)

**Comment by jsw945** [comment]
# 班级信息


* 班级编号：004
* 班级名称：力学笃行
* 班级口号：认知升级，刻意练习

---

# 班级LOGO
![此处输入图片的描述][1]


  含义：LOGO使用的概念是著名物理学家薛定谔提出的思想实验——**薛定谔的猫**，象征作为参与新媒体运营学习的我们，敢于跳出我们的舒适区，身处未知，拥抱不确定性，然后达到认知升级。外面的盒子是比较简单的矢量图，和我们所处的世界一样是有边界的，猫撕破了盒子来查看外面的世界，形象是更为细致和具体的，有个明显的反差效果，凸显了“通过现象看本质”的哲理。LOGO以黑白两色为主色调，简单又不失冷静，沉稳，专业。
  
---
# 成员名单

* 金贇，来自福建，从事文职工作，担任小班班长，希望自己**越努力，越幸运，让自己的精神和灵魂更加丰富起来**，喜欢刷微博热爱一切新鲜资讯，是一个负责任有担当的金牛座！
* 郭伟韬，来自湖南，在校大学生，担任应用传播学课代表， 目标是**寻找新媒体中的第一性原理，通过可以练习提高自我认知**，兴趣是互联网资讯和游戏，是班组里具有智慧的文案才子！
* 耿源，来自云南，在上海证券公司实习，担任新媒体营销理论和实战课代表，她的理想是**成为一代女侠**，是一个拥有职场新鲜人坚定的斗志，热爱生活，努力成长的正能量女生!
* 林琳，来至湖北，从事文案编辑工作，担任新媒体创意写作课代表， 她希望**让想象力长出翅膀勾出属于自己的篇章**，是一个喜欢看漫画刷微博看综艺，超迷韩国演员李准基的软妹子！
* 李慧君，来自湖北，是一名少儿英语教师，担任新媒体产品设计课代表，她希望能在训练营里**踏踏实实学习一项技能，结交志同道合的朋友**，现在知名教育机构任职，是个不甘平庸，有志向的灵魂工程师！
* 毛维才，来自云南，现在是一名客栈老板，担任新媒体终极排版课代表，他认为**人与人之间的距离就是几本书的距离**，喜欢航拍，更喜欢广交朋友，是一名热爱家乡并积极推广云南独特美景和人文，一腔热忱投身于旅游事业的优秀创业者！

---
# 成员风采
我们班组比较特殊，来自五湖四海不同省份，所在的地方距离都远且各自工作都比较忙碌，相比其他班组来讲是一个明显的短处，线上线下活动相对困难。所以能聚集一起也是非常不容易的事情。不过反过来想想，愿意在忙碌工作之后的学习的成员们，都是有着一颗挑战自我，不断学习的进取心，所以我相信，我们的班级是最棒的！ ![此处输入图片的描述][2]


  [1]: http://upload-images.jianshu.io/upload_images/9507052-94a23e1e3d759a93.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/512
  [2]: http://upload-images.jianshu.io/upload_images/9507052-c4db19e140d7bd25.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/700

**Comment by Wh1tePaper** [comment]
## 班级

- 编号：5
- 班级名称：爷巡山
- 班级口号：合谋造梦，聚众私奔。
- 班级logo：
![9](https://user-images.githubusercontent.com/34528589/34235829-35bf9418-e62f-11e7-9a9d-f2de4d2940e5.jpg)

### 含义：
**爷巡山：** 取自夜巡山的谐音。

白天，芸芸众生，苟苟营生，或梦或醒，生活和梦想都交给了眼前所谓的光明，除了妥协的智慧，还有被迫的将就。

夜晚，万籁俱静，万物消停，或生或死，我们却能在黑暗里醒来，灵魂主宰意志，寄情天地，纵渺沧海，可谓生而快活，死亦何惧？


**合谋造梦：**

代表我们每一个人都有自己的灵魂梦想，不论原因，不论距离，能凑在一起，就是此生莫大的机缘。

我们能在一起守望相依，彼此成就他人梦想，这就是最大的美好，最妙的缘分，俗称：**真他妈的爽！**


**聚众私奔：**

有了机缘，有了梦想，我们需要去做，不能耍嘴皮子，要知行合一，所以呀，私奔永远是一件让人向往的事情，可谁也做不出来，古代是要浸猪笼的死刑。

那么，私奔要的是**生的勇气和死的勇敢**，这寓意着我们将坚定不移，勇冠三军，无坚不摧，甚至还可以**拐走别班的人跟我们浪！**

**logo:** 
一群猴子加一个妹子，七圣上天山，闭眼去巡山，以梦为马，开心就好。

----------


## 班级成员风采

**成员名单**

| 姓名| 坐标 | 职业 | 课代表 | 自我介绍 |
|----------|------|------|--------|----------|
| 张东亮 | 连云港 | 平面设计师 | 微信终极排版指南 | 一个想打造自己技能体系的人。 |
| 隋志博 | 墨尔本 | 跨境电商创始人 | 新媒体故事结构入门 | 守正用奇；弱水三千但取一瓢；桃李不言下自成蹊。 | 
| 姜媛 | 北京 | 户外旅游 | 新媒体产品设计 | 生而为人，请务必善良。一个肆意生活任性妄为的人。 |
| 阿木 | 苏州 | 影视创作人 | 内容营销理论与实战 | 把自由和信仰活到骨子里的人。 |
| 李月 | 苏州 | 视觉爱好者 | 新媒体创意写作 | 少即是多 | 
| 王吉恒 | 南京 | 体制内 | 新媒体传播应用学 | 专注当下 |


----------


## 成员风采
![8](https://user-images.githubusercontent.com/34528589/34235841-454c248c-e62f-11e7-92c1-22817d31d33b.jpg)


----------

**Comment by truebloodFan** [comment]
# **班级信息**

- 编号：T03

- 班级名称：新新人类

-  班级口号：学无止境 新新向上New media，creative ideas.

- 班级iogo: 含义：我们新媒体人把信息分享给世界连接世界，世界会听到我们新新人类的声音。
![sa](https://user-images.githubusercontent.com/34603237/34303601-1e7a9440-e771-11e7-8a32-e0ff478d731d.png)



## **成员名单信息：**


- **朱莉**:微信终极排版指南课代表 -来自深圳，从事企宣工作。所有的事情，都是阴差阳错。半撇私塾，是通过我之前常来的网易云课堂认识的。因为对这个课程还比较感兴趣，所以我来了做人最紧要乐观。


 - **火鸡茵**:新媒体创意写作课代表 -来自澳洲凯恩斯，不过其实是成都人同班同学请不要说广东话，我听不懂的。现在是做旅游景点的市场营销,急需弄明白新媒体怎么搞。爱好是非常宅的桌面扮演游戏和动漫,。


- **陈壮志**:新媒体故事结构入门课代表- 成功的速度一定要超越香奈儿出新包的速度。会唱歌会弹吉他会打篮球，最擅长的技能可能是打篮球。通过不断远离舒适区的方式来提升自己的水平，比如选气较少的球来练运球，让自己处于喘气的状态下练投篮。


- **吴星睿**:内容营销理论与实战课代表 -来自广东陆丰，目前体制内工作，爱好旅游和摄影。特立独行。



- **胡红林** :新媒体产品设计课课代表- 来自广东深圳，目前从事个性定制化项目的市场营销，如企业工作服，活动T恤，帆布袋等个性产品定制；想学习新媒体营销相关知识提升自己文案写作和策划能力；乐于交朋友，爬山，跑步。



- **陈啟立**：新媒体应用传播学课代表-作为一个专业的小屌丝，没几样拿出手的，就会弹点小吉他，尤克里里，爱好烹饪。汽车维修保养是专业的。对汽车的构造还是很熟悉的可以点评车辆哈哈!



- **小德拉**：广东省深圳市光明街道（红烧乳鸽的圣地）感受和书籍是我灵魂的一部分，使我每日如新生。回过头来，人生每日如新生，那是不是就不害怕衰老和死亡？读文学作品时，会起鸡皮疙瘩。


## **成员风采展示**
![6](https://user-images.githubusercontent.com/34603237/34303597-140c4774-e771-11e7-8220-99af9b7ef2cb.jpg)

**Comment by peihaoran** [comment]
# 班级信息

- 班级编号：T02
- 班级名称：有一班人
- 班级口号：得闲饮茶
- 班级logo&含义： 
![Alt text](http://upload-images.jianshu.io/upload_images/9549416-98a9821d54f542a8.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
有一班人，来自天南地北，从炎夏能披厚外套的东北黑龙江，到寒冬可穿薄衬衣的岭南广东；
有一班人，被联合国归为中年人，却自认韶华仍在，并信仰最灿烂的青春只会在学习与奋斗中划过。
有一班人，不约而同地选择了半撇私塾的新媒体运营专业课，在常住人口达1400万的羊城遇到彼此。这是最坏的时代，有一班人，在茫茫人海中，在繁忙的都市中，前几辈子好不容易积攒下来的回眸，在地铁高峰期一次便不得不超额兑换成无疾而终擦肩而过。但这也是最好的时代，有一班人，不用成为冤家，从最初即是为了共同的目标作为可爱的小伙伴相伴在彼此身旁。
还所幸，有一班人，共同热爱着广府文化，我们相约，得闲饮茶。
饮茶是广府文化中别具特色的一个符号。饮茶在广州不仅仅是泡一壶茶，而是有一班人相聚一桌，品味香茶和精美的茶楼点心，三五知己聊聊天。有一班人，得闲饮茶。并非期待天天得闲，活成闲人，而是有一班人，热爱广府文化，并饮茶视作自己生活的美好的一部分，无论多忙，心底里总有一片净土留给自己所爱，而且饮茶的乐趣还在于有三五知己，谈天说地。得闲饮茶寄托着我们对志同道合者的向往，有一班人总是愿意相信，向前永不停歇的步伐，会让我们遇到更多更可爱有趣机智的小伙伴。

# 班级成员风采

![Alt text](http://upload-images.jianshu.io/upload_images/9549416-7f4f0dff1406e694.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

## 成员名单

| 姓名             | 坐标           | 职业  | 课代表 | 自我介绍 |
| ------------- |:-------------:|:-----:|:-:|:-:|
| 裴浩然 | 广州 | 教育培训 | 内容营销理论与实战 | 一个没什么特长，特别爱吃的胖子 |
| 陈雅婷 | 广州 | 游民 | 新媒体创意写作 | 一个开始感叹时光易老的当代中年少女，想趁一切还来得及，记录下身边早已习以为常的人事 |
| 袁晓芬 | 广州 | 英语教师 | 新媒体故事结构入门 | 一个喜欢学习和探索的傻姑娘 |
| 邓婷月 | 广州 | 朝九晚五的市场经理 | 新媒体产品设计 | 喜欢浪迹天涯去旅行。一张去哪都觉得好玩，吃啥都觉得好吃的满足脸。 |
| 郑家凉 | 广州 | 学生 | 微信终极排版指南 | 欲戴皇冠，必先承其重 |

**Comment by Lucky-Six** [comment]
班级：006

班级名称：雄鹰队

班级口号：雄鹰，雄鹰，展翅高飞

**Comment by Lucky-Six** [comment]
班级：006

班级名称：雄鹰队

班级口号：雄鹰，雄鹰，展翅高飞
