### ISSUE TITLE
我的自我介绍

### ISSUE THREAD

**Issue by dahai169** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#105]
###1.基本情况

***

* **名号：**大海
* **坐标：**北京
* **简书个人主页链接：**[我的简书](https://www.jianshu.com/u/2228ae21b1a3)
* **生命故事：**我来自四川，现在工作在北京，喜欢有挑战的事情，喜欢独自背包旅行。我曾经坚定的相信，只要自己足够想做的事，就一定能做好！从事目前这份工作已经快4年，在经历工作中的重重磨练以后，我越来越清楚的意识到自己发展的瓶颈，越来越迫切的需要提升自己的专业能力。恰好在无意中注意到咱们这个课程，几乎没怎么过多的考虑就报名了，我希望通过学习，使自己以后在处理这方面工作的时候，能够更加专业和效率，并能够把工作做得更好、在实际工作中产生更大的价值。

###2.技能介绍

***
* 制定计划，这算吗？在很早以前独自旅行经历中，慢慢养成的习惯。我的方法是找到自己足够想做的事，然后投入精力去做，并且要有目标和时间意识。那么在做的过程中，自己为了在时间范围内达到目标，自然就会逼迫自己去想怎样做，那么慢慢的就会养成计划的习惯。

###3.输出计划

***

* 目前正在用farbox和简书，farbox记录心情日记，简书记录学习笔记。

###4.利器推荐

farbox，这是个非常方便的个人博客网站，支持markdown语言书写。所有博客在本地以txt文档保存，网络自动同步更新，非常方便书写和利于保存。

**Comment by fang-yu** [comment]
报道要跟帖回复哈，我先关闭这一条帖子。
