### ISSUE TITLE
自我介绍

### ISSUE THREAD

**Issue by sophia1111** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#106]
<h2 id="toc_0">自我介绍</h2>

<p>大家好，<br/>
我叫 回归的孩子，<a href="https://www.jianshu.com/users/025ea86ca114/timeline">简书</a>上的昵称也是它。目前坐标广州，在一家教育培训机构工作。</p>

<p>之所以起这样一个名字，只是想不断提醒自己不忘初心、方得始终。2014年9月份，我辞掉了北京的工作，因为一直忙忙的状态让自己有些心力交瘁，更多的是茫然。对自己而言，我更倾向于多问自己几个为什么，我想知道自己是谁、从哪里来、又要到哪里去，看似没有答案的哲学终极三问我也想用自己的体验略探一二。因缘际遇下在武汉参加了一个名为黄庭禅的禅修课程，原本对两天的课程没有抱太大的希望，却不料就此改变了我的人生轨迹。 </p>

<h2 id="toc_1">为什么参加半撇私塾</h2>

<p>知道半撇私塾，是我无意间在网易课堂上官网上看到的，原本并没有在意，但因为自己心里一直想建立并运营一个自己的的公众号，却苦苦寻不得既专业又系统的培训课程，于是多看了两眼具体介绍就立马决定报名了。之前也陆陆续续接触过不少关于微信公众号运营的各种课程文章，但总感觉流于表面，一定有更科学更深入的内容可以挖掘。</p>

<p>半撇私塾吸引我的有两点。</p>

<p>第一点，我是比较喜欢探究事物的本质，对流于表面的现象事件总想探究这背后的理论模型，究其根本，因为抓住主轴才能万变不离其宗，半撇的几大模块设计就有坚实的理论基础，至少给我指明了要探究的方向。</p>

<p>第二点，项目制的学习方式很赞，边学边做远比只是听课来的收益多、体验深。</p>

<h2 id="toc_2">最擅长的一项技能？</h2>

<p>平时喜欢画视觉思维图，不管是读书还是听课，经常会抽出时间把学到的东西进行反思沉淀，用视觉思维图的方式呈现出来，既清晰又深刻。</p>

<h2 id="toc_3">未来的输出计划</h2>

<p>1.两年内学习 黄庭禅 国学经典15部，写多篇学习心得画多篇视觉思维图。<br/>
2. 三年内写就系列书 三步曲</p>

<h2 id="toc_4">推荐利器</h2>

<p>软件 幕布，做关键词大纲笔记很不错，电脑端、移动端都适用且同步，很是方便。</p>

**Comment by fang-yu** [comment]
报道要跟帖回复哈，我先关闭这一条帖子。
