### ISSUE TITLE
大家好，我是废柴君

### ISSUE THREAD

**Issue by feichainongshe** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#107]
# 我是**废柴农舍**，大家可以叫我**废柴君**
![](https://ws1.sinaimg.cn/large/0061Xju4ly1fn1ihgidy0j30ku0k8n4j.jpg)

**Comment by fang-yu** [comment]
入学报到在这里回帖哈：https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/4
