### ISSUE TITLE
入学报告

### ISSUE THREAD

**Issue by Marshallzcy** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#108]
# **自我介绍**

* **名号**
        　　　　马歇尔
* **坐标**
        　　　　洛阳
* **简书**
                　　　　  [我的简书](https://www.jianshu.com/users/c4bbb1dc495f/timeline)刚刚想在简书上发文发现链接插入没有任何反应，还没摸索出为啥..
* **生命故事**
　　　　　普通编导专业出身，刚刚失恋加失业（好吧其实失业也是因为失恋+公司），心酸的异地恋啊..
颓了一周在彻底死心的某个夜晚重新规划了自己未来两年的路，把新媒体运营作为之后的职业方向，打算在学完课程后奔赴京城北漂 。都说失恋是最好的修行期，不借着这个机会让自己变得更优秀，怎么再遇到更好的人。再过五个月就24了，必须得搏一搏了。  

# **技能介绍** 
　　　　　1. 简单的PR 学编导的，剪辑还是会点皮毛     
　　　　　1. 因为自己爱录歌 自学的AU
　　　　　1. 架子鼓.. 说唱 
![wiz](http://i1.973.com/ri/1499046100404.jpg)

# **输出计划**

　　　　　1. 自己运营一个微信公众号，粉丝自然是越多越好，如果有时间还会帮朋友的公众号更新几篇文章练手。
　　　　　2. 当然是顺利完成训练营所有课程，更重要的是能掌握所学的知识
# **利器推荐**
　　　　　知乎：从这里我找到了你们这么好的课程这还不够利吗！！？？
　　　　　keep：这个应该很多人都知道，算是最良心的健身app了

**Comment by fang-yu** [comment]
入学报到在这里回帖哈：https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/4
