### ISSUE TITLE
自我介绍

### ISSUE THREAD

**Issue by Johnny-XIE** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#115]
### 自我介绍
-----

1. 大家好我是**JohnnyXIE**，非要说个名号的话......以后写东西都会用**「我吃饭不爱玩手机」**吧～		
		
		很多同志问我为什么叫这个名字？		
		很简单，因为我吃饭的时候真的不玩手机啊，这就是个事实而已。
	
	好了，说完了，基本所有需要用到名字的地方除了户口本身份证，都是这两个了。

2. 坐标 *「广东深圳」*，身为一名 *「福建人」* 表示每天都生活在担心被吃掉的焦虑中。

3. [简书 Link](https://www.jianshu.com/users/6be35340e865/timeline)。慢慢会学着更新一些内容，当然了，不一定是大家都喜欢看的就是了哈哈。

4. 2017 年 07 月本科毕业后，我从福建厦门来到深圳，要说为什么？其实当初想的很简单，那时候我很清晰的知道自己不喜欢在厦门工作的感觉，节奏太慢，混日子的人太多，我概括为环境太 **「腐朽」**。	
	
	选择深圳，主要是向往快节奏、充实、学习、奋斗从而走向人生巅峰的生活，也比较喜欢大都市的感觉。还有一个就是离家人比较近，以前去福州上大学，动车 2 个小时 25 分钟到，深圳回家，3 个小时 40 分钟到，会让老人家比较安心，起码是可以短时间触摸到的距离，想我了随时可以来，我也可以随时回家陪他们。说一下自己工作，我在深圳一家创业公司做新媒体运营，其实也是刚刚转岗到这个职位，不过是我自己选的。	
	我没有选择继续做擅长的 BD 工作，而是选择全新的未知领域，随之而来的已然是每天巨大的压力，在学习的同时，还需要以最快的速度把所学用到工作上；同样，在工作时，遇到的问题，也要通过尽可能快的速度保质保量的学习，然后解决工作上遇到的问题。	
	越长大越懂得脱离舒适区去生活，年轻，代表着最不怕辛苦、学的最快、最有灵性的时候，这个时候更要勇敢的脱离舒适区去每时每分的进步。所以，说实话，我现在真的很开心，每天除了训练就是工作。	
	
	对了，忘了说了，我最大的爱好是「健美」和「力量举」，这是我的信仰来的，而且我挺猛的，年底要去参加深圳的健美锦标赛了，想想就激动！	
	
	![IT'S DREAM COME TRUE!](http://johnnyxie-tuchuang.oss-cn-shenzhen.aliyuncs.com/18-4-4/33459284.jpg)	
	
	我的梦想就是成为一名 IFBB 健美运动员，然后有一个属于自己的健身品牌，不只是卖衣服裤子，而是做一个像「MUJI」一样的，它是一种生活方式。	
	
	参加半撇私塾是为了之后自己创业，再就是现在的工作，既然我选择了，就要负责把这个事情做好，对公司是一种价值贡献，对自己也是一种成长，而且我觉得真的很有趣，所以～

### 最擅长技能
-----
+ **我最擅长的技能应该就是说服别人的销售能力吧。**		
因为小时候很爱吹牛逼，满嘴漂亮话，但闽南家庭长大，闽商那套客套我反而最排斥，所以我觉得，谈判合作就是「完全真诚，然后采取激进的策略」，这也是我从耐克创始人——Phil Knight 的《Shoe Dog》里面看到的观点，然后发现自己俨然已经是这种模式，之后便更加去强化运用了。	
	
	学习方法论，我觉得这门技能的方法论就是多和思维方式跟你不同、格局更大的人交流，生活工作中留心观察。在向别人销售你的想法或者产品的时候，如果你能实现「降维打击」，就会更加容易赢取信任从而实现合作，不是说你满口听不懂的高大上词汇，而是从思想上有着领先和更深远的思考，那么自然就会有着巨大说服力。
	
	至于语言方面就是平时要大胆阐述、表达自己的想法，你会发现，为了让人们能更快更轻松地、完整清晰地理解你想表达的意思，你会在言语上不断的做调整，尽可能简短精炼，从而进步。
	
### 输出计划
----
+ 我会在「简书」分享我学习这门课程的整个心路体会，还会更新我在工作上实际运用的全过程包括结果。

### 推荐利器
-----

|工具|**推荐理由**|
|:--|:--------:|
|Teambition|用过最棒的团队协作工具，可以在上面实现所有需要多人协同的工作内容|

*大家晚安，耶巴蒂！*

**Comment by YeziGZ** [comment]
@Johnny-XIE  自我介绍放置位置错误，把你的自我介绍内容粘贴到[「【训练营】入学报到：一起探索全栈新媒体人的世界！」](https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/109)帖子下，在该帖子下方跟帖回复即可。
