### ISSUE TITLE
新人报到

### ISSUE THREAD

**Issue by XiaoJingone** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#116]
# 自我介绍

## 名号：小晶

（再不学习就要没饭吃了，说得就是我，捂脸）

## 坐标：深圳

欢迎来深圳大坪山玩儿，这是隶属深圳地区中物价最美丽的地方～～～

## 简书：

[阅读笔记](https://www.jianshu.com/u/df90606afaa3)

大多是读书笔记，字码了不少，但颇有囫囵吞枣之嫌[捂脸]

所以，半撇动手实践的理念特别适合我！

# 故事

> 正走在，女汉子蜕变为女神经的路上。

毕业四年有余，转行一年左右，之前三年半一直在一家大型民企浑浑噩噩混日子。后来，有一次在外出徒步路上同伴遇险，忽觉生命可贵，便横了心，不管不顾就是要 换工作。

紧接着迎来颠沛流离的一年换工作，半年内连续搬家4次，两份新媒体工作都不出彩。临着第二份工作离职前，被大boss评价可能不适合做文案工作（内心一万句想吐槽），但只跟他说，我喜欢这个，也一定会做好的（虽然心里也没多少底，但咱既然说了相信自己能做好，就要死磕到底）。

哇咔咔，有木有很帅！

理工科基础，非任何一家社交软件重度用户，码字水平放在原来的环境还能拿得出手，但转行到新媒体就是大巫见小巫了。之前也没有很好的转行调研，中间经历的两家小公司也无法给我行业指导，总之越做越迷茫。认真思考后，认识到最重要的是能找到一个带我入行的人，在知乎上搜索来到了半撇，比较了馒头商学院、插座学院的课程后，为决定还是来半撇，理论知识对我的益处已经不大了，希望在这里能与半撇一起为彼此见证奇迹！

> 习惯了仰望星空的人，可不想双脚永远都陷在泥潭里。

> 找份工作不难，难的是能做自己选的工作！

# 技能介绍

瑜伽，报了线下课程，后来为了自己也能在家练，就索性上了导师班。

哈哈哈，咱们半撇肆不肆也可以有**导师班**哇。

![倒立](http://yuewenshiji.oss-cn-shenzhen.aliyuncs.com/18-4-5/10845112.jpg)

现在，业余时间教室友瑜伽，然后惊奇地发现为了教好她，我练习得更加卖力啦！[奸笑]

私以为有两个原因，一是要不断重复说练习口诀，不自觉地自己练习时也会更加认真；二是，两个人相互监督，谁都不愿意先偷懒。

其它技能，好像都跟日常生活相关，是个能把小日子过滋润的人，但是跟时尚貌似就比较远了。

**还有一个很奇怪的技能就是——跟我玩得好的人，好像都长得特别好看，哈哈哈！**

# 输出计划

1、每周一篇学习周总结，在简书输出。

2、目前待业，原计划2个月学完整个课程，看了小伙伴们的介绍后，我觉得要提前到一个半月学完！

# 利器推荐

1.[一千零一夜](http://m.youku.com/video/id_XMzQ5NTMzODAzNg==.html?from=s1.8-3-1.1&source=)：

梁文道先生制作的一档视屏节目，解读古今中外文学经典；读书的好处是能让我们安心，无论身处何方。

2.[奴隶社会](http://mp.weixin.qq.com/s/YQv1bZX5hrSnQDkvAPq0ow):

![奴隶社会](http://yuewenshiji.oss-cn-shenzhen.aliyuncs.com/18-4-5/47066797.jpg)

最近非常喜欢的一个公众号，安利给身边好友后，本来有点丧的她跟我说，看了这里面的文，觉得还是值得好好生活的。

PS：这个公号的创始人也在做教育，她说**从娃娃抓起，教育才是让这个社会变得更好的第一生产力。**

**Comment by YeziGZ** [comment]
@XiaoJingone  自我介绍放置位置错误，把上述自我介绍内容粘贴到[「【训练营】入学报到：一起探索全栈新媒体人的世界！」](https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/109)帖子下，在该帖子下方跟帖回复即可。
