### ISSUE TITLE
【Graduation】Let's Party！A Hacker's Journey

### ISSUE THREAD

**Issue by YeziGZ** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#2]
Hey！

这里是毕业项目提交的地方。

请确保你的毕业项目已经完成了自检：

- 包含了核心要点；
- 运用了通俗易懂的语言描述，
- 包含了个人产品链接（博客／简书／公众号／知乎......）

当你完成自检的时候后，将毕业项目在此提交吧！

记得使用Markdown写作语言。

做是最好的学。

**Comment by WildPandaLee** [comment]
Panda 的毕业项目：http://www.jianshu.com/p/da3d06b8eaa5

**Comment by YeziGZ** [comment]
@WildPandaLee 学习不是一段短暂的旅程，而应是伴随一生的使命，学会学习则是一生的命题。即使毕业，也要一直坚持学习，加油！Panda
