### ISSUE TITLE
这是我用markdown写的第一篇文章？

### ISSUE THREAD

**Issue by zhuhualun** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#23]
#很高兴参加半撇私塾的学习
大学是学工科的，毕业之后的两年，做了线下半流动性的展览。
做了两年之后辞职，本来想要转行学UI设计，不知怎么的误打误撞就入行了新媒体。
可能是因为觉得自己没有什么美术基础，又比较喜欢写一点什么东西吧。
大概的情况就是这样。

这次参加半撇私塾想要得到什么？
*学会做内容，依靠原创的内容每篇可以涨粉几十个。
*学会写产品推广软文，通过产品推广软文可以实现卖货。
*交到志同道合的小伙伴。

**Comment by fang-yu** [comment]
仔细查看作业说明，提交错误哈，我 Close 掉这一条issue。
