### ISSUE TITLE
从零开始

### ISSUE THREAD

**Issue by johnXD1** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#24]
#### 在好几门微专业的课程中，最后选定了**全栈新媒体运营**，第一次拼团成功的时候，因为在上班没有看到，没有加入成功😢，第二次拼团秒成功，果断付款，加入组织😊。
```
在报名这个课程之前，也购买过很多付费学习内容，但课程都属于自学，大多数的内容只提供一段音频，
什么时候想学习了就学习一下，不想学的时候就可以让这个app躺在手机里睡觉。
没有什么考核和测验，一切都靠自觉。

这门课程却不同了，每一节课程都有时间限制，让我有了紧迫感，
我必须要在课程截止前学习完，并且还要完成相应的考试题，
学习性和认真程度有了很大的提高。


```
#### 希望自己在课程结束后的收获

* 从一个零基础的小白到一个了解新媒体运营知识的大白😄，然后在工作中不断的实践和巩固所学习到的知识。

* 在班级中可以认识更多志同道合的朋友，共同学习交流，共同进步💪。

* 能够更流畅、简洁的表达自己所要描述的观点。**努力做到说的东西让小学生都可以听懂**。

![1_140926012747_1](https://user-images.githubusercontent.com/29350658/27009656-5861a282-4ec6-11e7-966c-8afc24589650.jpg)

**Comment by fang-yu** [comment]
@johnXD1 注意查看微专业的课时说明哈，Makdown 练习场的任务在：https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/8 。 我需要 Close 掉这个 issue 了。

**Comment by johnXD1** [comment]
我总共发了两份，一份是在自己的主页上，还有一份是在老师发帖的#8帖子下跟帖的哈，那个是正确的吧







------------------ 原始邮件 ------------------
发件人: "方宇";<notifications@github.com>;
发送时间: 2017年6月11日(星期天) 晚上8:34
收件人: "BPteach/Full-Stack-New-Media-Hacker-Bootcamp"<Full-Stack-New-Media-Hacker-Bootcamp@noreply.github.com>; 
抄送: "john"<364979487@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [BPteach/Full-Stack-New-Media-Hacker-Bootcamp] 从零开始 (#24)




@johnXD1 注意查看微专业的课时说明哈，Makdown 练习场的任务在：#8 。 我需要 Close 掉这个 issue 了。

**Comment by fang-yu** [comment]
@johnXD1 我看到你在练习场的回复了，是正确的。下次一定要注意跟着课时的提示来操作哦，不然可能会回在作业互评时出现问题，加油。
