### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by ljhhzj** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#25]
# 大家好！
很**高兴**认识大家！先来做个介绍吧！
## 自我介绍
我来自大西北一个很适合生活的小城市——*武威*，一个人们不知道但知道了都很向往的城市。羡慕了吧！你可千万别来，因为我怕你来了就不想走了。
## 学习目的
我喜欢我的家乡，我喜欢新媒体！但我是一个小白，我想知道新媒体是怎样运营的，我想让大家多一点了解我的家乡！

**Comment by fang-yu** [comment]
注意查看微专业的课时说明哈，Makdown 练习场的任务在：#8 。 我需要 Close 掉这个 issue 了。
