### ISSUE TITLE
船头舵的自我介绍

### ISSUE THREAD

**Issue by Doshine** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#26]
# 自我介绍

>“我听别人说这世界上有一种鸟是没有脚的，它只能够一直地飞呀飞呀，飞累了就在风里面睡觉，这种鸟一辈子只能下地一次，那一次就是它死的时候。”

**名号：**大家好，我叫船头舵。期待有一艘自己的大船，随风去远航。独自字船头掌着舵，背影留给夕阳。

**坐标：**我在丽江，我是纯正的纳西族，我的灵魂属于玉龙雪山。请不要误读丽江。

**简书：**[船头舵的简书](http://www.jianshu.com/users/df252c2dda7b/timeline)（目前还是空空如也，以前不太习惯在公共空间写东西，以后加强）

**生命故事：**大学毕业已经十一年了，经历了无奈，拼搏，痛苦，坚持。渐渐磨砺出自己的性格，风格和属于自己的空间。目前是两家企业的负责人。

***

**为什么参加半撇私塾：**自从有网易云课堂以来，我就经常喜欢在这个平台上找些有意思的课程进行学习。有一天，我找到了半撇私塾的课，试听了几节，感觉很有意思，也很有内容。所以就准备买。刚要买的那天，发现半撇私塾出了微专业，正好就买了微专业。巧的是，刚买了微专业，就正好有一个本地自媒体的项目需要我们去做，那正好需要用到这一套课程的知识了。

***

#技能介绍

***

**网络维护与网站搭建：**当年在上海的时候，每天早晨七点起床上班，下午五点下班后去上课，九点下课后回家看书到晚一点，周末也在上课。

***

#输出计划

***

以前的确很不习惯在公开的平台或公众视野下写东西，现在借着这门课，希望能不断突破自己，把自己的思考和专长在简书和本地平台上写出来。目前的初步计划是：
1、每周至少在简书上写一篇文章
2、定期整理学习笔记，把自己的学习笔记做成一个小栏目
3、用本专业学到的知识运用到本地自媒体的运营中去，把学到的东西教给整个运营团队。

***

##推荐利器

***

1、**多态**
2、**云墙**
3、**[翻滚熊猫（推荐）](https://pandafan.org/)**
**_以上都是亲测好用的VPN软件，可惜都是付费的。需要的同学可以试试。（ps：云墙需要先用其他vpn翻墙才能下载，而且无法在windows系统中使用）_**

**Comment by fang-yu** [comment]
微专业入学报到在这里哈：https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/21，注意查看说明哦，我先关闭这一条issue了。
