### ISSUE TITLE
初识半撇

### ISSUE THREAD

**Issue by zaminji** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#27]
初识半撇
***
可能是天生的不踏实，我一直尝试着新的东西并不断充实。

高中时期，因喜欢画画走向了艺考这条路，然而，系统接受正规培训后，我开始慢慢厌恶，因为我讨厌每天被人逼着做一些俗不可耐的事，在那段时期我觉得我已经失去了原有的灵活思想，我甚至画不出我以前想表达的那些无比花哨的东西，所以，我并不觉得绘画适合我。

上了大学的我，在无意中接触了微信公众平台，不知为什么，有一种一见钟情的感觉，我开始从各种途径学习新媒体，也确实学到了不少东西，但还是不够系统，所以，我希望可以学到更多。

很多人叫我熙泽，可能是因为我QQ网名、微信名都叫这个吧。据我估计，叫我熙泽的人比叫我本名的人多得多。

我很喜欢我的学校——中北大学，她给了我很多空间让我学习我喜欢的东西，也给了我平台让我走的更广，所以，我不想辜负她。在学习完课程后，我想从整体上对我运营的平台进行系统的整改，并且将富有创造性的思想留给学弟学妹们。

未来的路还很长，我依然是个“小学生”，但我希望我可以以一个新媒体人的身份在这个社会中立足，可能我做不了设计师，但设计中所学习到的各种内容我会以最大程度运用到新媒体中，我有我的优势，我也会战胜我的劣势。

能够参加半撇我很开心，能与大家一同学习我很放心，在这个行业中，我相信我。

我可能接触的太少，懂得的也太少，很多东西没有接触到，所以也就不误人子弟了。

>有人说：生命中有一些人与我们擦肩了，却来不及遇见；遇见了，却来不及相识;相识了，却来不及熟悉，熟悉了，却还是要说再见。

我是熙泽°，熙泽有度~

我的简书链接：[熙泽有度](http://www.jianshu.com/u/d37cfd5ab28d)

欢迎关注我的个人微信公众号，你关注了我会很开心的：

![](http://upload-images.jianshu.io/upload_images/6393057-a22df17dc5b34bcb.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by fang-yu** [comment]
注意查看微专业的课时说明哈，Makdown 练习场的任务在：#8 。 我需要 Close 掉这个 issue 了。
