### ISSUE TITLE
写给当下的自己

### ISSUE THREAD

**Issue by dawenguo** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#28]
> 三天前开始的课程今天才开始看，错过了竞选班长的机会。
### 写在前面
* 初识新媒体这个概念在16年，当时也不知怎地，微信公众号突然摇身一变就成了新媒体，此时据我接触微信公众号已一年矣。后来慢慢知晓新媒体是一个包罗万象的词，涵盖了微博、微信公众号、头条号等社交、内容平台在内的一切不同于传统的媒体形式的即是新媒体，当然从狭义来说，新媒体指向微信公众号，新媒体运营即微信公众号的运营。
* 后来，自己在这方面逐渐深入，从一个懵懂无知的小小屁孩到一个初识皮毛的小屁孩。通过书籍，各种相关课程的学习，自己好歹也算是入了门。有一天在网易云上看见这个新媒体运营的课，毫不犹豫的就买了，虽然花了1000多还是有点小肉疼。期待这个课程能让我对新媒体的有一个更深刻的认知。

### 我自己的新媒体
* 注册微博久矣，一直觉得微博、微信朋友圈和早期的QQ空间并无二致，都是在一个平台上发布自己的想法感慨，为啥要同时在几个地方一起发。多无趣。
* 注定是自己年少无知，越成长越明白，它们其实并不一样。不然也不可能活这么久还没倒下，印证了“存在即合理”的真理。
* *个人微博 [位末言微](http://www.weibo.com/2411452803/profile?rightmod=1&wvr=6&mod=personinfo)，欢迎大家点击链接访问。*

### 最后
希望在为期3月的学习中，和众多小伙伴一起成长，遇见一个更好的自己。

**Comment by fang-yu** [comment]
注意查看微专业的课时说明哈，Makdown 练习场的任务需要在：#8 完成。 我需要 Close 掉这个 issue 了。
