### ISSUE TITLE
My Markdown Mannual

### ISSUE THREAD

**Issue by ljlovecat** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#29]
# 自己做一份manual玩玩
>我是李璟，本硕就读于东南大学，2018年毕业。金融二级市场卖方研究员实习干了6个月，发现入行的机会太少，全年全行业留给应届生的缺口估计不足50人。俗话说居安思危，如今我已立于危墙之下，怎能不思变？果断转行互联网，备战3个月，奋斗9月秋招，愿届时有所收获。

直接隔一行，就从正文开始了

## 标题
>* 标题有两种语法格式，Setext语法格式，和atx形式。前者使用=做一级标题标识符，-做二级标题标识符
* atx语法格式，即使用#作为标题标识符

## 列表
>列表分为无序列表和有序列表。如果要在引用中使用无序列表，必须在首行就开始。
无序列表使用*，-，+作为标识符，三者的功能都是一样的
* 不在首行就没用？

现在在首行来一个
>* 你看，有了吧
>+ 当然，用+号也是可以的
>- -当然也可用

来一个有序列表玩玩
1. 有序列表咯
2. 好像只能用数字来玩?也行吧

## 代码区块
用```码代码
```
代码区块
if you are SB
End if
```
## 分割线   
使用三个以上的*或者_，来建立一个分割线吧
___
***
两条分割线啦啦啦

## 超链接来一个
>使用[] ()，中括号就会链接到括号中地址
使用![] ()插入图片，利用云图工具可以通用啦

[我的母校](http://www.seu.edu.cn/)
![](https://ooo.0o0.ooo/2017/06/14/59408d0e80332.jpg)

**Comment by fang-yu** [comment]
注意查看微专业的课时说明哈，Makdown 练习场的任务在：#8 。 我需要 Close 掉这个 issue 了。
