### ISSUE TITLE
班级介绍

### ISSUE THREAD

**Issue by salt-nilin** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#32]
- 编号：019

- 班级名称：蓉聚新媒

- 班级口号：蓉聚“心”媒，用心改变生活。

- 班级logo：

- ![image](https://user-images.githubusercontent.com/29419344/27114394-f221e798-50f5-11e7-80ff-edd7b2862675.png)

- 含义：成都，在这里——用心媒传新媒
**# 班级成员风采**
成员名单

- 王楸郁：班长，成都、学生。爱好：没有固定爱好，喜欢尝试不同的新事物，葆持一课少年好奇心。

-  符洪源+新媒体应用传播学、新媒体产品定位课代表+成都+产品+摄影、羽球、烘焙，爱好广泛却浅尝辄止的微宅

- 林墨含/创意写作+故事结构课代表/成都/职业:半导体工程师/爱好:阅读、写作、旅行/

- 黎彦曦/内容营销理论与实践课代表/成都/职业：创业者/爱好：

# **第一次会议**
线上wechat——2017.6.13
“蓉聚新媒”进行了第一次的线上讨论。来自五湖四海、同聚成都的小伙伴们讨论了关于班级初期建设问题。进行了有趣而让人印象深刻的自我介绍。在这个有爱的“小家庭”中每个人都担任着不可或缺的角色。希望在未来长达一个季节的学习生活中，能够更好地诠释成都这座城市与新媒体的相互交融，更好地实现自我。

**Comment by fang-yu** [comment]
注意查看微专业的课时说明哈，班级报道任务在：https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/22，需要重新提交哈，我先 Close 掉这个 issue 了。
