### ISSUE TITLE
Struggle for a better future

### ISSUE THREAD

**Issue by Braveheart1216** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#35]
> 我曾经认为自己是个太空人，我花了好长一段时间，才发现我只是一名星球之间的寂寞舞者。
——前苏联的宇航员

# 关于我
我是谁？我从哪而来？这是一个宇宙间永恒的命题。归根结底，人不过是宇宙间的沧海一粟。
我叫程玉其，出生于安徽南部的一个农村，早些年家乡满眼是田野的风光。如今随着城镇化的进程，镇上开发了温泉旅游，如今更多了商业气息。高中以前，我一直生活在这样一个相对闭塞的环境，倒也心无旁骛，从小的我就是一名热爱学习的好学生，长大后依然是这样。知识改变命运，这是一条真理。希望自己通过不断学习，遇见一个更好的自己。

## 我的兴趣爱好
![](https://ooo.0o0.ooo/2017/06/14/59415205baf86.png)
跑步

![](https://ooo.0o0.ooo/2017/06/14/59415281ae3be.png)
旅行 

![](https://ooo.0o0.ooo/2017/06/14/594152a2eb054.png)
交友

# 关于职业
> 选择了一个职业，就是选择了一种生活方式。

毕业后做了两三年的编辑记者，刚转行做新媒体运营，纯小白一枚。新媒体运营远比我想象中的要复杂琐碎得多，不仅要对产品和用户有足够的了解，还需要有一整套完善的思维体系和对运营工具的熟练掌握，如:**文案写作、公众号排版、用户管理、增粉、阅读量提升等等**。坦诚地说，这行入门容易，想要做到精深和专业，体现自身的含金量却很难，大多的运营还是停留在初级阶段。所以，系统深入的学习就显得十分重要。半撇私塾项目制管理的方式吸引了我，这有别于市场上其他同类产品，我也希望自己能坚持学习，收获满满。

# 关于明天
希望自己通过三个月的磨练，在半撇私塾掌握新媒体的看家本领，十八般武艺样样精通。最后拿到高薪，迎娶白富美~
- 新媒体排版
- 打造自己的新媒体公众号，媒体矩阵
- 作图
- 软文高手
- 内容营销，打造自己的品牌

**最后，用一句话总结：将来的你，一定会感谢现在奋力拼搏的自己。青春就是用来挥洒汗水，用来折腾的，不是吗？**
![](https://ooo.0o0.ooo/2017/06/14/5941589880698.png)

**Comment by fang-yu** [comment]
注意查看微专业的课时说明哈，科学上网练习场的任务在：#7，需要重新提交哈，我先 Close 掉这个 issue 了。
