### ISSUE TITLE
Braveheart: Freedom Speech

### ISSUE THREAD

**Issue by Braveheart1216** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#36]
https://www.youtube.com/watch?v=hIvRkjOd1f8
> 他们或许会杀死我们 ,但他们夺不去我们的自由! 自由！

第一次看《勇敢的心》是在大学英语的课堂上，当然就被这影片中的场景深深震撼了：对于华莱士，自由是深入骨髓里的东西，即便是会被敌人杀死，但是自由是夺之不去的东西，是神圣不可侵犯的。回溯近代中国的历史，无数仁人志士为了中华民族的自由抛头颅撒热血，杀身成仁，不也是同样的道理吗？自由，自由，自由，不仅是身体自由，更是灵魂的自由，人格的独立，为自由追魂永远都需要！

**Comment by fang-yu** [comment]
注意查看微专业的课时说明哈，科学上网练习场的任务在：#7，需要重新提交哈，我先 Close 掉这个 issue 了。
