### ISSUE TITLE
初识全栈新媒体运营课程

### ISSUE THREAD

**Issue by qiheng2017** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#37]
# 初识全栈新媒体运营课程

纠结了很久，终于在近期下定决心重新开始自己的人生，当然还谈不上创业啦！只是寻着自己心目中的一个方向前行。作为一个长期从事行政工作的人，从未接触过新媒体运营领域，我总觉得这是属于90后的世界。哈哈，我进来啦，70后大叔在抢90后小朋友们的饭碗！当然不至于啦，只是想好好学一学这个既熟悉又陌生的平台，以后自己的事业基础应该离不开这个舞台。

也算学了三天吧，粗谈一下自己的感受。

## 学以致用

> - 在学习的过程中，“输出”要大于“输入”。
> - 教是更好的学。
> - 做是最好的学。

我们都经历过手把手的学习技能，比如做饭、开车；也长期经历过翻着一本本教材、老师讲授而被动接收的填鸭式学习。回过头来发现，还是那些用到的，自己记住了，而从来就没有再用过的，大部分都又交还给了老师。所以你真正想学、想记住的东西就一定要用起来，所谓的**刻意练习**。为此，我刻意强化自己的输出。除了注册简书账户外，也开通了第一个自己的微信公众号。整个过程都是在不断学习的经历。更新几天下来，发现确实挺辛苦的，而且微信公众号更新特别是修改起来太不方便，所以除了已成型的文章外，一些体会感悟等还是喜欢通过简书发布。为了用Markdown语言发布第一条自己的简书文章，自己趴在谷歌的Chrome浏览器上，硬是埋头啃了一个下午。对于我这种零基础、大叔级的人来说还算可以接受的吧！

## 翻墙头，体验刺激与快感

> 为了最大化利用最优质的学习资源，我们需要学会“科学上网”来访问一些可能被屏蔽的网站，也就是我们常听说的“翻墙”。

第一次看到“翻墙头”被这么高大上的评价，真的让我有些忍俊。自己可是体制内的小乖，听说过但从未敢尝试过翻墙看看外面的世界。通过一阵简单但有些手忙脚乱的设置以后，终于翻出来了。哇，谷歌浏览器好简洁啊，我都不知道该怎么去找按键，什么铺天盖地的广告、乱七八糟的新闻全都不翼而飞。用谷歌搜索第一时间就能找到我希望看到的东西，就好像摆脱了雾霾一样，感觉浑身轻松。

## 独立思考，不断成长

> - 学习不是一段短暂的旅程，而是一项终身的使命。
> - 要像骇客一样思考：一是学会偷懒，二是学会搜索，三是学会用工具解决问题。

其实让我下定决心离开现有安乐窝的最终决定因素，就是我确定了自己下一个职业方向，就是做一名学生，以追求终身学习为职业。手把手教和从书本上学，这都是比较传统的学习方式，在知识大爆炸的时代，更多新的知识和技能是没有办法完整呈现出来的，知识和技能本身也在不断地丰富和完善过程中，因此需要我们学会自主学习、独立思考。互联网就是这样的一个教室和舞台。在这里我们会运用各种搜索和工具把点滴的、支离破碎的知识点汇集成自己的知识体系，并且通过自己的独立思考，剔除鱼目混珠、颠倒黑白的糟粕，从而不断积累成长。

## 自学者的世界不寂寞

> 你将会像英雄一样完成这一段学习旅程，经历大小的挑战，最终你会收获属于自己的胜利。

好莱坞的英雄题材影片都有相对固定的故事结构，大都来源于神话学大师约瑟夫.坎贝尔的《千面英雄》。现在，现实中的我遇到了困境或者挫折，按照英雄之路，接下来我会在另外一个世界开始修炼。这里的修炼之路既有趣也充满了挑战，会像上学一样分小组、分工，每周都有相应的学习任务和Quiz，并要按时保质保量完成里程碑作业和课程考试。有同学之间的互助协作，当然也充满了竞争。希望自己在新的世界里经过三个多月的训练，可以出关接受新的挑战，开启我的英雄之路。

**千面英雄，在学习者的世界里，大家都是英雄。**

![](https://ooo.0o0.ooo/2017/06/15/5941e15727e72.jpg)

**Comment by fang-yu** [comment]
Hi， 非常用心的体验哈，不过如果这是练习场的作业，记得发布在对应的Issue下面才能通过考核，注意查看微专业的课时说明哈，科学上网练习场的任务在：#8，需要重新提交哈，我先 Close 掉这个 issue 了。
