### ISSUE TITLE
视频作业

### ISSUE THREAD

**Issue by qiheng2017** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#38]
[Magical Lego Train DreamRide](https://youtu.be/h5ltIXyaLno) 
之前从来没有在YouTube看过视频。第一次尝试很新鲜但也找不到什么自己太喜欢的东东。这个小视频是众多初选中自己最喜欢的。一帮无聊却又追求极致的烧友们搭建迷宫一样的场景，让一辆小火车什么的在轨道上穿梭，感觉自己变小了，周围都是既熟悉又陌生的世界。类似的也看过一些，这个更酷炫，特别是有个场景，小火车慢慢穿过一排电脑主机，打开的DVD光驱像一扇扇大门依次关闭，怎么做到的？喜欢这些烧友的极致精神！

**Comment by fang-yu** [comment]
注意查看微专业的课时说明哈，科学上网练习场的任务在：#7，需要重新提交哈，我先 Close 掉这个 issue 了。
