### ISSUE TITLE
程玉其自我介绍

### ISSUE THREAD

**Issue by Braveheart1216** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#41]
**1. 自我介绍**
我叫程玉其，网名潇湘雨，来自于美丽的 **“周瑜故里 温泉之乡”**——*合肥市汤池镇*，这里山清水秀、空气清新、民风淳朴，如果你来这里玩，我一定会热情地当好一个导游，让你尽兴。
我大学学习的是新闻传播学，大学里学过摄影、摄像、播音主持、新闻采访，毕业后有幸从事相关的职业。如今的我是一名新媒体运营的小白从业人士，希望在这个方向持续走下去。
我目前负责公司的新媒体运营项目，与高速出行有关，运营的公众号名称是“行云天下”，提供ETC充值、出行提示、优品商城相关内容，感兴趣的可以去关注一下。至于简书，是自己刚刚注册的，所以没有什么内容，后续会开始创造。附上链接，互粉哦~ [简书](http://www.jianshu.com/users/897b18d2518a/timeline)
参加半撇私塾是因为自己本身就喜欢学习，加上半撇的理念吸引了我，所以及毫无悬念地参加进来了。

**2. 技能介绍**
技能这一块不好意思上台面，因为自己的天生嗓音条件比较好，加上锻炼普通话，看相关朗诵和主持视频，大学里当过播音与主持协会的负责人，有过几次主持的经历。也是学生时代难忘的记忆。可惜毕业后就没有再做过相关的事情了，也就只能作为一个兴趣爱好，希望以后还能有机会有用武之地吧。

**3. 输出计划**
目前是给公司做新媒体运营项目，还没有自己的相关输出平台。
所以，接下来准备在简书上和微信公众号有所产出，保证每周至少有一篇产出。从零开始打造一个公号。

**4. 利器推荐**
做运营，俗称打杂，但是还有很多的KPI和数据需要背负，有时候压力是很大的。压力过大需要宣泄才好，有没有什么健康的方式？之前在网上看到一款减压骰子，觉得十分有意思，分享给大家。
![](https://ooo.0o0.ooo/2017/06/15/59428d8fcb4de.png)
就是这个神器了，别看它小，功能可多了，有**按钮、摇杆、凹槽石、滚动、拨盘**……各种方式供你把玩，供你蹂躏，我觉得这些方式有些类似于我们紧张时搓手或者咬手指的小动作，这个骰子把压力揽到了自己身上，颇有牺牲精神。值得尝试~

**Comment by fang-yu** [comment]
学员介绍需要在：https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/21 完成，需要重新提交哈，我先关闭掉这一条issue。
