### ISSUE TITLE
传播学应用场景研讨

### ISSUE THREAD

**Issue by Attackchen** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#42]
1、工作沟通更高效，使沟通双方能快速理解认可。
2、活动文案更走心，使用户更愿意参与与分享。
3、小到职场交际花，大到网红代言人。能够提升个人、品牌影响力，创造独立IP。

**Comment by fang-yu** [comment]
注意查看课时说明哈，提交链接在：https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/9
