### ISSUE TITLE
半撇学习第一更

### ISSUE THREAD

**Issue by vigouraven** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#43]
# Say Hi
我是04班的**小邝**是一个喜欢讲段子的代购兼产品助理，工作方向是成为一个独当一面的*产品经理*。
![](http://wx2.sinaimg.cn/mw690/a38b66f0gy1fg4dz7gycnj211i11kgzg.jpg)
                                                               
                                        （求关注新浪微博：丶小邝）

## 最喜欢的一句话
>生活不只是眼前的苟且，还有诗和远方。

**Comment by fang-yu** [comment]
注意查看课时说明哈，Markdown 练习场在：https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/8
