### ISSUE TITLE
举个栗子

### ISSUE THREAD

**Issue by vigouraven** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#44]
[有樓萬事足 ](https://www.youtube.com/watch?v=BoiC-ug8hN0)

这部片子真实地写出了香港市民在看待买房这事儿上态度，同时也间接表明了中国在发展到一定经济水平后也将进入同样的尴尬境地，买房真的要乘早！（我不是房产中介哦）

**Comment by fang-yu** [comment]
Hi，注意查看课时说明哈，翻墙练习场的提交链接在：https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/7，我先关闭这一条issue。

**Comment by vigouraven** [comment]
是我发错地方了😨吗？

2017-06-15 23:15 GMT+08:00 方宇 <notifications@github.com>:

**Comment by fang-yu** [comment]
是的，应该发送在https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/7
