### ISSUE TITLE
【原创】从初创企业的成功要点中发现新媒体运营的几点启发

### ISSUE THREAD

**Issue by miczhong** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#48]
# 为什么要用创业来说事？

>作为一个10多年来慢慢变成非知名的互联网创业老司机（其实就是做得不怎么样的还美其名曰：“连续创业者”），所以在这里很想和大家分享，但是局限于水平不足，只好借助一些高人的知识点来扩展一下自己的认知。

经过了这些年来互联网的沉浮跌宕与高速变化，确实应了那句话“**唯一不变的就是变化**”。我们处在的是一个不确定性的世界，新媒体的到来让我在混沌的创业过程中找到了一丝希望，互联网通过新媒体的载体变得更有影响力和传播力，如果掌握一部分或者说是进入到这个新媒体运营的“圈层”，认识更多的朋友和老师，更有利于我未来的项目开展，所以我来了！

与其说是创业，更接近的应该说是一个项目比较恰当。随着移动互联网的蓬勃发展，各种直播、微博、微信公众号、简书、喜马拉雅等等媒体工具的广泛应用，新媒体运营想要好，就需要以一个项目来思考，那就是和创业如出一辙。为此我们先来看看Anna Vital做的“初创企业如何成功”图示给咱们的启发。

![](https://ooo.0o0.ooo/2017/06/16/59436b2937360.jpg)
图片版权来自：[anna.vc](http://anna.vc/about)

## 挑选好的联合创始人（合作伙伴、团队）
>对于初创公司来讲，团队就是唯一能打造项目的资产了，团队成员的要是选得不好，结果甚至是倒闭关门，因为所有的事情都是靠团队来完成的。

那我们来看新媒体运营的团队当然也是非常重要，**团队成员能够在自己负责的板块独挡一面，高效运作**。很多关于团队方面的思考与管理创新应用，大家可以看看这本书，希望有所帮助。
[《敏捷革命》:提升个人创造力与企业效率的全新协作模式](https://book.douban.com/subject/27008697/)

## 快速发布项目（MPV）
>说到“快速发布项目”，并不是说要快速把产品投放进市场，而是说，只有当你真正将想法付诸行动之后，才表明你真正在工作了。无论你要做什么，先去做！无论你能给什么用户体验，先给！接触用户永远是第一要务。

新媒体运营同样也要**不断的把想法付诸行动，通过用户的反馈调整策略，小步快跑、不断试错**。

## 让想法持续进化
>快速启动项目后，持续的产品迭代、快速响应。**初始创意实现之后就结束的想法，这是绝对错误的！**创业就像写作，大多数的绝妙创意都是在执行过程中不断迸发出来的。

新媒体运营过程中的**跟踪、反馈、改进就是一个创意的过程，让创意不断实现和印证的过程**。

## 理解你的用户
>你越理解用户，你创业成功的几率就越高。这就是为什么许多成功的创业公司最初做的产品，就是创始人自己需要的产品——因为经过切身体会，自己最理解自己的需求。

新媒体的每一个内容应该是一个对用户**“有用”**的内容，真实的为客户提供了他们想要的。**无论是一段文字还是一张照片亦或是一条语音一个视频，只要是“有用”为指导核心，那你就错不了：），当然可不敢把这个弄成了“伪需求”**。

## 供养一批属于自己的粉丝（让一部分用户真心爱你）
小米的粉丝开始只是从喜欢在论坛里帮助小米修改MIUI的用户，他们希望自己的安卓手机界面能好用，不断的参与MIUI的讨论和改进，从而成为了“自己的产品”。“为发烧而生”的口号也是为了这帮喜欢“折腾”的粉丝定制的，开启了：**让一部分用户真心爱你！**。在新媒体运营过程中，我们同样需要打造属于自己的粉丝圈，不断的为他们服务和改进，让他们也爱上我们（好像就是在谈恋爱）。

##  令人尖叫的用户体验（提供令人惊讶的良好用户服务）
说到用户体验，其实就是一个服务客户的过程，笔者总结下来就一个词“用心”。无论是“海底捞”或者“顺丰速递”，还是“海尔”，他们开始的竞争力就是“服务”，用心服务。目前很多的互联网公司纠结的用户体验是软件层面、UI设计界面，这其实远远不够，**这个是一个系统化的工程，我们可以称其为“服务设计工程”**。从公司的方方面面，小到一个电话接听、大到一个活动策划执行，**都能让您的用户感受到“用心”，这就是“超值的令人惊讶”的服务了**。我们做新媒体如果弄清楚这个要素，在运营过程中的很多问题其实都非常容易解决，只要问一句“我们这样做有没有用心为用户着想？”，应该就很容易找到答案了。

## 一分钱掰两半花（省着花钱）
>其实这里说的省着花钱，不仅仅说的是节约公司的开支，更重要的是一种思维方式。当然创业公司来说，节约是非常非常非常重要的。（重要的事情说三遍）。节约的文化可以使一家公司保持活力，就如同轻断食能使人年轻，大吃大喝会使人贪婪又懒惰。

这个思维方式在新媒体运营或者公司运营中也是非常重要的。**我们要利用现在手上有限的资源，不断的让自己有更多的想法去解决“因为没钱”而不能做到的问题**，让自己的思路可以打开，而不是变成思维定式，从而可以**发现或者创造出与众不同、自带流量的模式**。

以上是我在看到创业成功要点的几条里边总结的一些想法和观点，希望对大家有所帮助，也希望能与我有更多的交流。文章最后有我的一些介绍和联系方式，期待与您连接。

最后，细心的您也会发现，图片作者用了很大的一块提到了**“综上所述，就是要理解您的用户”**，所以关注用户需求是我们的首要。

钟波（悦乎） miczhong | 021班新媒体产品定位课代表
------------ | -------------
非知名互联网行业创业者 |  [Thinkbow Ltd.](http://thinkbow.com)董事
喜欢的两句话 | Think big, Think different；一切皆有可能
微信小号 | thinkbow01

**Comment by fang-yu** [comment]
感谢你和我们非常你的原创文章！不过 Markdown 练习场的作业需要在 https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/8 完成，注意查看说明再次提交哈，我先关闭这一条issue。
