### ISSUE TITLE
学最好的别人，做最好的自己

### ISSUE THREAD

**Issue by anthelion79** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#49]
> 19世纪末期，外国科学家认为，人类所能达到的运动极限速度是80几公里，而这也就是超越可能的根基。

　　就事论事的说，因为那时跑的最快的汽车也跟本达不到那种水平，所以制造不断先前的速度是衡量一个车好坏的重要标准，而汽车生产厂商也寻求了突破，1901年，也就打破了这一说发，当时的那种水平所制造的汽车时速都在五六十公里，85公里那都应该是科学家能吹则吹的数字，有数字，就有突破，现在，80公里，成了大多高速公路上的最低限速。有理由相信，有虚夸才有与虚夸相等的现实。
　　但，成功往往还是现实的，现实的成功来自于创新，那就是要培养，创新型人才，感尝试型人才，更多的，把机会留给这些人，因为，将来的世界属于他们!
　　成王败寇一念之差，创新，就是风险的附带品，也就是没有几个真正创新成真的，多是研究失败的意外偶然产物，这些附属品，反倒成了当今世界的主流文化。信仰来源于对于成功的理解，就像马克思主义一样，人类的生活最后共产化，这也是必然的趋势，那么，这就是理解对了，要注重信仰，就要学会自我认知，理想也许是永远不会实现的，但是不会实现的理想有些是废料，有些，又成了高度物质文明的垫脚石，有可能，这垫脚石还附着弹簧，它，能发挥无穷大的力量，有些，你不能完成的理想，把他公之于众，或许是你没想到，或者不真的有这个能力，当别人恰好知道了你这个理论时，他也就可能把你的理想现实化，共享的好处遍地流金，这也就是成功者的自我树碑立传。

### 想要完成理想，就首先要完成现实虚拟化。
首先，你要触类旁通，把一个现实从固有理论，像夸张甚至是可笑方向扩展，使其有灵活的运用空间，足够的知识，十足的能力，理论不是一成不变，大多数理论，也只是大多数人进过实践、实验、觉得确实可用的多相情愿，但如果你的理论，比上述原有理论更加实现化，更加有说服性，那就说明，你创造了新理论，新概念。
### 创新是不断升级的
开着兰博基尼，用着智能手机，玩着便携式网络终端，想想过去的马车、飞鸽传书、和土算盘，你就会觉得，是成功者的创新，把你现在所拥有的绝大部分东西以看似不可能再到让你习以为常地呈现。

　　成功者的有点就是可以更灵活的，更轻松的存于世界。成功固然是美好的，但，过分的攀比，过分的最求，却会让你本已经攀地很高，却因弓过自蹦而摔落于起点。有些时候，才需要“知足”。往往成功之后，却因种种，失去了最平常不过的也是最简单的幸福，那时你追寻的不是成功，是忧虑。
　　通往成功的路不止一条，然而用的交通工具，也就是原则不能轻易改变，成功者也并非一定要树碑立传，去让人效仿，因为，**走自己的路成功，最爽**。

**Comment by anthelion79** [comment]
> 19世纪末期，外国科学家认为，人类所能达到的运动极限速度是80几公里，而这也就是超越可能的根基。

　　就事论事的说，因为那时跑的最快的汽车也跟本达不到那种水平，所以制造不断先前的速度是衡量一个车好坏的重要标准，而汽车生产厂商也寻求了突破，1901年，也就打破了这一说发，当时的那种水平所制造的汽车时速都在五六十公里，85公里那都应该是科学家能吹则吹的数字，有数字，就有突破，现在，80公里，成了大多高速公路上的最低限速。有理由相信，有虚夸才有与虚夸相等的现实。
　　但，成功往往还是现实的，现实的成功来自于创新，那就是要培养，创新型人才，感尝试型人才，更多的，把机会留给这些人，因为，将来的世界属于他们!
　　成王败寇一念之差，创新，就是风险的附带品，也就是没有几个真正创新成真的，多是研究失败的意外偶然产物，这些附属品，反倒成了当今世界的主流文化。信仰来源于对于，功的理解，就像马克思主义一样，人类的生活最后共产化，这也是必然的趋势，那么，这就是理解对了，要注重信仰，就要学会自我认知，理想也许是永远不会实现的，但是不会实现的理想有些是废料，有些，又成了高度物质文明的垫脚石，有可能，这垫脚石还附着弹簧，它，能发挥无穷大的力量，有些，你不能完成的理想，把他公之于众，或许是你没想到，或者不真的有这个能力，当别人恰好知道了你这个理论时，他也就可能把你的理想现实化，共享的好处遍地流金，这也就是成功者的自我树碑立传。
### 想要完成理想，就首先要完成现实虚拟化
首先，你要触类旁通，把一个现实从固有理论，像夸张甚至是可笑方向扩展，使其有灵活的运用空间，足够的知识，十足的能力，理论不是一成不变，大多数理论，也只是大多数人进过实践、实验、觉得确实可用的多相情愿，但如果你的理论，比上述原有理论更加实现化，更加有说服性，那就说明，你创造了新理论，新概念。
### 创新是不断升级的
开着兰博基尼，用着智能手机，玩着便携式网络终端，想想过去的马车、飞鸽传书、和土算盘，你就会觉得，是成功者的创新，把你现在所拥有的绝大部分东西以看似不可能再到让你习以为常地呈现。
　　成功者的有点就是可以更灵活的，更轻松的存于世界。成功固然是美好的，但，过分的攀比，过分的最求，却会让你本已经攀地很高，却因弓过自蹦而摔落于起点。有些时候，才需要“知足”。往往成功之后，却因种种，失去了最平常不过的也是最简单的幸福，那时你追寻的不是成功，是忧虑。
　　通往成功的路不止一条，然而用的交通工具，也就是原则不能轻易改变，成功者也并非一定要树碑立传，去让人效仿，因为，**走自己的路成功，最爽**。

**Comment by fang-yu** [comment]
Hello: 注意查看微专业的课时说明哈，Markdown 练习场的任务在：https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/8 ，需要网页下的评论中直接提交哈，我先 Close 掉这个 issue 了。
