### ISSUE TITLE
很好听

### ISSUE THREAD

**Issue by dingyanyiren** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#52]
[宇多田ヒカル - 二時間だけのバカンス featuring 椎名林檎](https://www.youtube.com/watch?v=UPdlfIhzPEo)这个MTV拍的很不错，女主妆容干净，微微沙哑的嗓音配合旋律，整首歌很有意境

**Comment by fang-yu** [comment]
Hello: 注意查看微专业的课时说明哈，科学上网练习场的任务在：https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/7 ，需要网页下的评论中直接提交哈，我先 Close 掉这个 issue 了。
