### ISSUE TITLE
做一个终身学习的人

### ISSUE THREAD

**Issue by yst66x** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#54]
# 做一个终身学习的人
## 原因
一直对微信运营方面的工作，对新媒体运营方面比较感兴趣。在网易云课堂上看到了《全栈新媒体运营》微专业就毫不犹豫地报名了。平时自己事情也多，希望能坚持完成这次学习之旅。
## 目的
- 提升写作的能力
- 提升讲故事的能力
- 学到新知识
- 拿到**毕业证书**
* * *
![](https://ooo.0o0.ooo/2017/06/17/59448168ac1b1.jpg)

**Comment by fang-yu** [comment]
Hello: 注意查看微专业的课时说明哈，Markdown 练习场的任务在：https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/8，需要网页下的评论中直接提交哈，我先 Close 掉这个 issue 了。
