### ISSUE TITLE
自我介绍

### ISSUE THREAD

**Issue by funny055** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#55]
##个人简介
* 姓名 ：肖峰
* 性别 ：女
* 职业 ：初级微信运营人员
* 目前居住地：北京
***
##个人风采
![清华北大一日游.jpg](http://upload-images.jianshu.io/upload_images/6421239-56a09555d6f7d493.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

##个人爱好
1. 重度电视剧迷，最近有跟我一起追《楚乔传》的吗？
1. 一直想好好学日语，过NI级，然后独自去日本生活一个月，体验下当地文化。
2. 平时喜欢打羽毛球、游泳。
- - -
##职业愿景
1. 我现在刚刚学着着微信运营，但是之前是完全没有经验的，希望在网易云这个微专业平台，收获新媒体这个行业专业性的知识和技能，为自己的职业发展奠定扎实的基础。
2. 未来一年内，写作能力up、思维能力up、对热点的追踪能力up、活动策划能力up、薪资10k+。
3. 给自己两年的时间，成为一个出色的新媒体运营人员，能给自己所在公司快速带来价值。

**Comment by fang-yu** [comment]
Hi：

Markdown 练习场的作业需要在 https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/8 完成，注意查看说明再次提交哈，我先关闭这一条issue。
