### ISSUE TITLE
半撇私塾，我来了!

### ISSUE THREAD

**Issue by Attackchen** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#57]
##为什么学习？##

-**当爸爸被抬进急诊室的那一刻，我发现父母已经老了...**

![](http://imgsrc.baidu.com/forum/w%3D580/sign=af3bb67f6163f6241c5d390bb745eb32/e86e544e9258d109eefa94f4db58ccbf6c814d10.jpg)

-**当她望着商场的橱窗欲言又止的那一刻，我发现我还是个穷小子...**

![](http://imgsrc.baidu.com/forum/w%3D580/sign=8a812a83eafe9925cb0c695804a95ee4/9e5e014f78f0f7361f6b7e470055b319eac4139c.jpg)

-**当同事业绩翻番被拍肩膀的那一刻，我发现我还是个只会三板斧的渣渣...**

![](http://imgsrc.baidu.com/forum/w%3D580/sign=4b63624e06d79123e0e0947c9d355917/f82b708b4710b912491fc4b8c9fdfc0393452257.jpg)

我开始思考如何打破这一现状，直到我看到这句话：

>这个世界就是马太效应。

你越牛逼，机会越多。

没有什么雪中送炭，这个世界只有锦上添花。

**你想要锦上添花，你得先变成锦。——咪蒙**

那么如何变成“锦”呢？只有不断的学习，不断提升自我，才是唯一的途径。

这也正是我加入半撇学习的原因。

##期待的收获##

加入半撇学习，我希望能在以下5个方面有所收获：

1.思维：拥有全面专业的社会化媒体传播思维。

2.方法：掌握更多软件工具的使用及实操技巧。

3.输出：能够学以致用，拥有独立完成撰写方案的能力。

4.圈子：期待与更多志同道合的小伙伴一起学习进步。

5.升职：通过努力，最终得到升职加薪的机会。

##小目标##

年龄（岁）|能力|月薪（元）

----|------|----

25 |撰写全案及谈判的能力| 1w

28 |带领团队做项目的能力|3w

30 |创办自己的乙方公司| 10w

##写给3年后的自己##

>HI,陈京！~

是不是又加班完，走在回家的路上？

我知道3年前的这个时候，

你还认为撰写方案，当众表达是一件多么困难的事！

唉，我要提醒你，你就是个22岁，身高1米82的巨婴

未来的一年是黑暗的，在这一年里你会失去娱乐消遣的时间去改变自己！

你会沮丧，你会无力。

我求你自己，你不能质疑你自己的能力

还记得当时刚入职场的时候，就被别人断定，

文字功底很差，做事效率很低。

可是，现在你加入了中关村管委会旗下的一家机构。

所以你不要浪费你自己的时间，怀疑你自己，加油！

没有一种坚持会被辜负。

希望你能够逐渐完成你的小目标！

然后接父母来到北京，看我未来的妻子。

时光是一场未知的旅行，此刻我不知道会走向哪里？

唯一确定的是我不会停下脚步！

##期待和你一起学习##

QQ:1635789830

微信：cjsos7890

[上车]( tencent://message/?uin=1635789830&Site)

**Comment by fang-yu** [comment]
Hi：
Markdown 练习场的作业需要在 https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/8 完成，注意查看说明再次提交哈，我先关闭这一条issue。
