### ISSUE TITLE
懿酱

### ISSUE THREAD

**Issue by YIJIANGSY** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#59]
# 自我介绍
 > weibo  “懿酱kikiki”
 > ins  “zoeyyy.sy”
 >手帐半年生，热爱生活，喜欢记录
 >喜欢美食、探店

#### 咖啡｜别止咖啡 besides＋cafe

别止，别致
玉皇山路，独栋小白楼
冷淡清新的色调，简单的北欧风
适合放慢脚步，呼吸绿色
因为幸运相识的一见如故的同龄伙伴
一同将小生活装进手帐📓

**Comment by fang-yu** [comment]
Hi：
Markdown 练习场的作业需要在 https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/8 完成，注意查看说明再次提交哈，我先关闭这一条issue。
