### ISSUE TITLE
新的开始

### ISSUE THREAD

**Issue by Serenarowe** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#60]
# **新的开始**
## 我要进步啦，像以前一样
>一毕业就在一家公司工作，从基层到现在，一干就是七年。在七年的时候突然迷惑了，想要有一个新的环境，新的开始。
>现在所有行业都会和线上的推广营销相关联，所以想要好好学习一下。这也是我的优点吧，我想要了解新的事物，但目前的环境下，所有的信息都是二手，时间久了，大家的思维模式也是一样。
>第一次通过半撇私塾的教学，学会了科学上网，学会了用MarkDown，感觉一下又高大上啦，喜欢.但Markdown Here，不知道怎么用，慢慢来吧。
>希望接下来三个月，有更多的进步
![](https://ooo.0o0.ooo/2017/06/17/5944c5be3182d.jpg)
**我的百天计划**
- 找到新的方向
- 学好一门语言
- 了解新媒体运营方式

**Comment by fang-yu** [comment]
Hello: 注意查看微专业的课时说明哈，Markdown 练习场的任务在：https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/8 ，需要网页下的评论中直接提交哈，我先 Close 掉这个 issue 了。
