### ISSUE TITLE
23班小萌新来报道

### ISSUE THREAD

**Issue by carolineHY** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#61]
#23班 小萌新来报道#

#####入坑新媒体，和小伙伴们一起愉快的玩耍！#####

>如果学习只在于模仿，那么我们就不会有科学，也不会有技术。—— 高尔基

- Name：黄颖

- Occupation：网络运营

###自我介绍###

*我是一个喜欢摄影、美食、绘画、旅游、电影的大龄文艺女青年，从事网络运营的工作很多年，但遗憾的是没有成功的运营案例，很多项目进行到一半死掉了，我也兼职做过品牌微信代运营的工作，对于新媒体我是比较熟悉的，但一直苦于工作没有突破性的进展，庆幸的是我在网易云课堂看到了这次的微专业，分小班制的管理让我非常惊喜，找到组织后和同学们交流很愉快，也收获了很多。*

**喜欢这样的教学方式，过去总是学的很多实践很少，然而做才是更好的学，与同学们共勉，一起进步，一起毕业，一起做我们喜欢的事。**

![](https://ooo.0o0.ooo/2017/06/17/5944d8886ae3d.jpg)

万事开头难，希望在以后的学习中能够遇到更好的自己。

​

**Comment by fang-yu** [comment]
提交错误，微专业小班级报到在 https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/22 下面跟帖。
