### ISSUE TITLE
每天进步1%

### ISSUE THREAD

**Issue by xcn007** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#62]
### 每天进步1%

**每天进步1%** 是丰田汽车工厂里的标语，也可以理解为企业文化。每个人都自己的理想和目标，同样我也有。工作5年，时常觉得很迷茫，不知道未来的方向。做什么事情贵在坚持，如同丰田公司的 **每天进步！%**，肯定会有质的变化。

**Comment by fang-yu** [comment]
你发布的地方错误了，注意查看微专业的课时说明。Markdown 练习场的任务在：https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/8 的评论中直接回复即可，我先关闭掉这个帖子。
