### ISSUE TITLE
守望先锋

### ISSUE THREAD

**Issue by daixudk** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#63]
# 守望先锋
## 组成
- moba
- fps
## 特点
-  *fps的技巧*
-  *moba的模式*

**Comment by fang-yu** [comment]
你发布的地方错误了，注意查看微专业的课时说明。Markdown 练习场的任务在：https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/8 的评论中直接回复即可，我先关闭掉这个帖子。
