### ISSUE TITLE
当我们谈起四六级时，我们在谈些什么？

### ISSUE THREAD

**Issue by hahaha416** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#64]
> *今天，各位无论年级的英雄好汉都聚在了一起，迎接一年两度的英语四六级考试，各位同学纷纷用不同的方式讲述了他们与四六级那些“不为人知”的故事，出了考场，我们又是一条好汉！*
## 1.诗歌体:
相见时难别亦难，拿到试卷好心寒。无边落木萧萧下，一片迷茫长对话。窗含西岭千秋雪，阅读完了不理解。醉卧沙场君莫笑，其实你也不知道。黄沙百战穿金甲，转眼要收答题卡。羌笛何须怨杨柳，考不出来咱就走。在天愿作比翼鸟，没过退款该多好。醉不成欢惨将别，明年再会各位爷。
## 2.葛优瘫式:
![](http://www.eyw.edu.cn/www//uploads/allimg/2017/02/23/-1-45371487839949.png)
## 3.鲁迅体:
我考过两次四级，一次考了424分，另一次也考了424分。
## 4.陈奕迅体:
在我有生之年考过四六级，竟花光我所有的运气。
## 5.雪莱体:
这次四六级考完了,下次还会远吗?
![](http://www.eyw.edu.cn/www//uploads/allimg/2017/02/23/-1-91301487840050.png)

**Comment by fang-yu** [comment]
你发布的地方错误了，注意查看微专业的课时说明。Markdown 练习场的任务在：https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/8 的评论中直接回复即可，我先关闭掉这个帖子。
