### ISSUE TITLE
视频推荐

### ISSUE THREAD

**Issue by hahaha416** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#65]
https://www.youtube.com/watch?v=bWGC5XD_68k
送给大家我最近无意中听到的一篇演讲——乔安娜·布莱克利：学习时尚界的自由文化
一个有趣的话题：
为什么版权的触角未能涉及时尚领域？
可是，时尚界真的需要版权吗？
这篇演讲会告诉你**正因为如此，时尚才得以在创新的基础上不断发展**

**Comment by fang-yu** [comment]
你发布的地方错误了，注意查看微专业的课时说明。科学上网的任务在：https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/7 的评论中直接回复即可，我先关闭掉这个帖子。
