### ISSUE TITLE
【微专业】自我介绍

### ISSUE THREAD

**Issue by hahaha416** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#66]
自我介绍

hi，大家好，
我叫佳芮，由于名字的容易被认错，朋友们也会叫我大饼。
我现在在大连读大学，携手大连度过我自己成人的第一段时光
参加了2个社团，体验过一段新媒体实习的工作，想要深入的钻这个领域，也对突破我自己很有兴趣。

为什么参加半撇私塾

知道半撇私塾是因为想要了解学习新媒体运营相关知识，下载了网易云课堂，就看见了，觉得介绍不错就学了。

最擅长的一项技能？
我兴趣挺广泛，但大多都是半斤八两，不过在活动策划方面，我极有兴趣，也考虑的很全面。

未来的输出计划
成绩成绩成绩！
组一个自己引以为傲的团队，干出一点事情！
读书读书读书！
推荐利器
强推得到！每天都听！爱罗胖！
就这些吧，期待和大家互相学习，共同进步。

**Comment by fang-yu** [comment]
你发布的地方错误了，注意查看微专业的课时说明。Markdown 练习场的任务在：https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/8 的评论中直接回复即可，我先关闭掉这个帖子。
