### ISSUE TITLE
做就是最好的学

### ISSUE THREAD

**Issue by MU-zi123** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#67]
# 做是最好的学
- 某天在逛知乎时，偶然发现了全栈新媒体训练营，看了很多相关的资料，然后就开始报名上课。刚打开热身项目的时候，就发现很多知识都是全新的，需要自己去实践操作，动手能力非常强的一门网上课程。真的是非常开始接触到全栈新媒体训练营，希望在以后更深入的学习中，能做的更好。

**Comment by fang-yu** [comment]
你发布的地方错误了，注意查看微专业的课时说明。Markdown 练习场的任务在：https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/8 的评论中直接回复即可，我先关闭掉这个帖子。
