### ISSUE TITLE
最喜欢的视频

### ISSUE THREAD

**Issue by MU-zi123** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#68]
https://www.youtube.com/watch?v=NIq0cMghn5U  《看见台湾||》是我喜欢的视频，之前拍摄的一是没有完整的看见的，导演把台湾的前世今日作为对比，今日的台湾和往日有什么不同，今天的台湾，与中国大陆，与国外很多地方作为对比和比较，在关于能源问题和环境问题上，做很多的分析和感悟，画面和画质真的拍的特别棒，给人心里的一种洗涤和反思。推荐给大家，希望大家喜欢。

**Comment by fang-yu** [comment]
你发布的地方错误了，注意查看微专业的课时说明。科学上网的任务在：https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/7 的评论中直接回复即可，我先关闭掉这个帖子。
