### ISSUE TITLE
治愈系列短片：黄啊玛的后宫生活

### ISSUE THREAD

**Issue by big-orange-cat** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#73]
[https://www.youtube.com/watch?v=Q6jsmRxQohM](url)是我超爱的类型，关于喵大人的生活，每个细节，不管多么细碎，都让人感到放松。
很简单，却很温暖。
工作治愈，看一段这样的片子，真的很幸福。

**Comment by fang-yu** [comment]
练习场作业发布在：https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/7

**Comment by big-orange-cat** [comment]
找不到……呜呜呜呜

在 2017-07-19 18:01:13，"方宇" <notifications@github.com> 写道：


练习场作业发布在：#7
