### ISSUE TITLE
毕业一年碎碎念

### ISSUE THREAD

**Issue by dwsonglina** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#75]
一晃眼，毕业一年多了，去年拍毕业照的情景依然清晰，但我着实已经进入社会一年了，这一年发生了好多事，认识了好多人，自己也因此成长了不少。

## 我的新媒体之路

我是学生物工程专业的，磕磕碰碰尝试了自己专业相关的工作，终于决定转行新媒体。然而转行并没有那么简单。

* 专业不对口
* 没有任何经验

但还是抱着试试看的心态尝试着找找工作，想面试官示意自己勤劳肯干，学习能力强，会很容易上手的，然而面试官似乎并不买账。

没办法，学呗！有作品拿出来才能顺利找到工作！

非常幸运，刚好在这时看到了半撇的招徒广告，经过一个多月的学习，主要是动手做项目，终于成功地找到了一份头条号运营的工作。九个月后顺利跳槽，终于找到了理想的工作，成功转行互联网。**真的非常感谢半撇，于是乎，时隔将近一年的时间我又回来了。**

这次的目标是三年后跳槽，年薪至少20w+，几个小flag，i can.

## 自卑与超越

>当一个人遇到无法解决的问题却深信自己能够解决时就会表现出自卑情节。

我有源自于原生家庭的自卑，我一直在尝试克服它。我相信只要你解决你自卑的原因，你便可以摆脱它。我龅牙，于是我去矫正牙齿；我长痘，我去钻研祛痘的办法；我不敢再众人面前开口唱歌，我去学习声乐……我一直努力着，希望遇见那个更好的自己。

按照惯例，最后应该有个二维码，刚刚去申请的淘宝达人号，还没有粉丝呢，你要做我的第一个粉丝吗？打开淘宝扫一扫吧，嘿嘿~

![img](https://i.niupic.com/images/2017/08/22/9hE6Kt.png)

**Comment by fang-yu** [comment]
Markdown 练习场需要在 https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/8 完成。

**Comment by dwsonglina** [comment]
方宇，见信好！
我前晚的课程，目前半撇私塾的人都联系不上，没有任何指引也没有进群，求解答




------------------ 原始邮件 ------------------
发件人: "方宇";<notifications@github.com>;
发送时间: 2017年8月23日(星期三) 上午10:21
收件人: "BPteach/Full-Stack-New-Media-Hacker-Bootcamp"<Full-Stack-New-Media-Hacker-Bootcamp@noreply.github.com>; 
抄送: "宋丽娜"<867534963@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [BPteach/Full-Stack-New-Media-Hacker-Bootcamp] 毕业一年碎碎念 (#75)




Markdown 练习场需要在 #8 完成。

**Comment by fang-yu** [comment]
请问你是标准版的学员吗？如果是，填写学号申请表后有如下提示：「填写完成后，请务必尽快添加助教微信（ID：xgclass），备注学号申请加入正式学员群！」。

微信群为学员交流，教学支持主要通过工单系统进行。

**Comment by dwsonglina** [comment]
是的，标准版。已经加了两天了，没有通过~可能因为没有备注学号？




------------------ 原始邮件 ------------------
发件人: "方宇";<notifications@github.com>;
发送时间: 2017年8月23日(星期三) 下午2:21
收件人: "BPteach/Full-Stack-New-Media-Hacker-Bootcamp"<Full-Stack-New-Media-Hacker-Bootcamp@noreply.github.com>; 
抄送: "宋丽娜"<867534963@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [BPteach/Full-Stack-New-Media-Hacker-Bootcamp] 毕业一年碎碎念 (#75)




请问你是标准版的学员吗？如果是，填写学号申请表后有如下提示：「填写完成后，请务必尽快添加助教微信（ID：xgclass），备注学号申请加入正式学员群！」。
 
微信群为学员交流，教学支持主要通过工单系统进行。

**Comment by banpie** [comment]
是的，因为助教每天添加的人太多，所以需要备注下你的学号，说明申请正式学员群以便加快快速处理。

**Comment by dwsonglina** [comment]
然而这已经是两天前的事情了~55555……




------------------ 原始邮件 ------------------
发件人: "半撇";<notifications@github.com>;
发送时间: 2017年8月23日(星期三) 下午2:24
收件人: "BPteach/Full-Stack-New-Media-Hacker-Bootcamp"<Full-Stack-New-Media-Hacker-Bootcamp@noreply.github.com>; 
抄送: "宋丽娜"<867534963@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [BPteach/Full-Stack-New-Media-Hacker-Bootcamp] 毕业一年碎碎念 (#75)



是的，因为助教每天添加的人太多，所以需要备注下你的学号，说明申请正式学员群以便加快快速处理。

**Comment by banpie** [comment]
非常抱歉，因为近期课程比较多，我已经联系了助教，让她帮你处理下。
