### ISSUE TITLE
王健林哈佛演讲：我自己的钱，爱往哪投就往哪投

### ISSUE THREAD

**Issue by dwsonglina** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#76]
在万达经历今年债股双杀，出售文旅项目就一直想看看他去年在哈佛的这个演讲了。不过感觉王健林确实蛮实在的一个人，但我自己的钱，爱往哪投就往哪投这句话听似没什么不妥，却也变成一个把柄，高处的事情实在搞不懂~

有兴趣的小伙伴也可以看下~

链接在这：https://www.youtube.com/watch?v=KhMP9aIlrfI

**Comment by fang-yu** [comment]
科学上网练习场需要在：https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/8 跟帖回复哈，我先关闭该贴。
