### ISSUE TITLE
别瑞commented on Aug27 • edited

### ISSUE THREAD

**Issue by bierui** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#77]
目的：卖掉一条裙子。
文案/话术：这条裙子剪裁特别，做工精良、你看这上面的刺绣、珠花都是纯手工的，布料柔软、舒适、亲肤。款式特别，穿出去，不会撞衫。高腰的设计拉长了您的 身材比例，将本来拥有好身材的你衬托得更加玲珑有致，一米八大长腿的既视感。女人要舍得对自己花钱，懂得宠爱自己，为自己投资，自己精致了，高贵了，别人才会为你买单，你的谈吐与气质值得穿这样的好裙子！
分析：该内容使用情感诉求和理性诉求实现说服目的。先从裙子的裁剪、做工、款式等作介绍为理性诉求，到最后从女性角度出发，强调女性要舍得为自己投资，这样别人才会为自己买单达到一个共鸣的心理为情感诉求。

**Comment by fang-yu** [comment]
练习场需要在对应帖子中跟帖完成，请查看具体的课时介绍，我先关闭这个issue。

**Comment by bierui** [comment]
好的，很抱歉！谢谢老师






在2017年8月28日 10:47，方宇<notifications@github.com> 写道：

练习场需要在对应帖子中跟帖完成，请查看具体的课时介绍，我先关闭这个issue。
