### ISSUE TITLE
bierui-commented on 28Aug

### ISSUE THREAD

**Issue by bierui** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#78]
1，通过传播学 的学习使得日常生活中沟通的更轻松，讲话有条理、不啰嗦、有重点、有逻辑。
2，通过传播学的学习让工作上的沟通更有效、竟而提高工作效率。
3，看问题、分析问题更加客观、全面。
4，写文案时能够鲜明地表达自己的观点、带动读者情绪、达到思想或心灵上的共鸣。
5，提高在公众场合表达能力，建立自信。

**Comment by fang-yu** [comment]
课程任务需在课时的对应链接中跟帖完成，我先关闭这条issue。
