### ISSUE TITLE
hello new media world---from Xintian

### ISSUE THREAD

**Issue by nicoleFZ** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#81]
# 基本情况
* 名号：心田
* 坐标：福建
* [简书个人主页链接](http://www.jianshu.com/p/b97f2e99ac69)
# 生命故事
我本来从事传统IT行业的项目管理，2年前转行到互联网行业，喜欢有活力、思维新的工作和团队，喜欢每天充电学习的生活方式。我对自媒体的工作充满好奇，所以参加新媒体骇客训练营，我赞同罗辑思维里所倡导的：个体可以充分展现自我，而不再依附于企业，在社会中绽放光彩。
# 技能介绍
嗯，我在我的专业领域已经做到专业级别了（当然还要不断提升）。生活中有：坚持了多年的瑜伽、每个周末为家人做美食、养些花花草草。
# 输出计划
get到课堂上介绍的每一个技能点和工具，应用到某个toB产品的运营中去。
# 利器推荐
* Evernote：我是高级账户成员，不仅因为它出现早、功能强大、很多应用都支持导出到它，而且因为它也在持续进行内容运营。
* OmniFocus: GTD的最好应用。
* Kindle：最纯粹的看书，用Kindle时就抛掉手机、抛掉朋友圈，给自己不受打扰的时光。
* 得到APP、喜马拉雅APP：每天路途上学习的必备APP，有了它们，上下班路途不再枯燥。

**Comment by fang-yu** [comment]
报道要在：https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/4 跟帖完成，我先关闭这一条issue。
