### ISSUE TITLE
【微专业第二期】小班级报到：找到你的学伴

### ISSUE THREAD

**Issue by YeziGZ** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#84]
## 什么是「小班级」

哈佛耶鲁、牛津剑桥等名校，给人最大的财富是在校期间的同辈压力与可以托付后背的同辈信任。随着人类知识的日益爆炸，我们不仅仅在青春期荷尔蒙旺盛的时候，需要同辈压力刺激。毕业后也一直需要一个能刺激自己发展的同辈压力环境。

我们坚信：同辈压力是最好的学习动力。见到别人那么努力，你不好意思堕落。所以在半撇私塾的学习中，我们也同样强调「同伴学习」。

>「同伴学习」是7个人所组成的小班级，可以是一个高效运作的团队，可以是相互帮助、并肩作战的学习挚友。7人成班，凝结一心。

所以在课程启动的开始，你们需要找到你们的「小班级」。

## 如何完成开学「小班级」任务

在开学第一周启动周中，需要「小班班长」在此Issue完成以下班级展示：

- 班级信息
  - 班级编号
  - 班级名称
  - 班级口号
  - 班级logo

- 班级成员风采
  - 成员组成信息：真实姓名+昵称＋担任哪个科目的课代表＋来自哪里＋职业＋一句话介绍
  - [可选]班级风采展示／班级第一次线上／线下见面活动

> 如果有机会，大家第一次见面可以采用线上或者线下的方式。

## 更多展示

当然，以小班的名义，你可以在这里发布：

- 小班成员的风采展示；
- 小班线上活动的精彩感言、总结；
- 小班线下活动的精彩照片、活动总结等；
- 小班的学习情况分享；
- 一切你觉得可以呈现出小班特色的内容。

### 更多帮助

1. [《微专业小班级管理指导手册》](https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/wiki/%E5%BE%AE%E4%B8%93%E4%B8%9A%E5%B0%8F%E7%8F%AD%E7%BA%A7%E7%AE%A1%E7%90%86%E6%8C%87%E5%AF%BC%E6%89%8B%E5%86%8C)
2. 想要认识往期班级？请点击查看[「全栈新媒体运营」微专业第一期班级风采展示](https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/22)。

**Comment by fang-yu** [comment]
举个例子

### 班级

- 编号：000
- 班级名称：东东枪小班
- 班级口号：做是最好的学。
- 班级logo：

含义：编号000，形状化成三个o，互相连接，凝聚在一起，象征着东东枪小班团结一致；三个o分别代表三个字母

  - Our：我们班级所有人；
  - Output：输出／做是最好的学；
  - Outstanding：每个人班级成员都是优秀、突出的小伙伴；

![](http://obfe8r4sl.bkt.clouddn.com/logo2.png)

### 班级成员风采

#### 成员名单（名字可用真实姓名或昵称）

- 刘念，应用传播学课代表，来自北京，体制内，逗比开朗；
- 陈欢，故事结构课代表；来自武汉，大四学生，清奇脑洞少女；
- 乌拉，新媒体产品定位课代表，来自广州，产品经理，不爱美食的产品经理不是优秀网络主播；
- S小姐，新媒体创意写作课代表，来自广州，大四学生，能写会逗新闻咖；
- ......

#### 成员风采展

![](https://ww2.sinaimg.cn/large/006tKfTcgw1fbja6lxxh4j30qo0f0q4w.jpg)

#### 第一次会议

2017年6月11日，东东枪小班进行了初次见面，虽然有两位小伙伴在广州之外的城市，但并不能阻挡我们小班成员间的热情。这一次的线上见面，大家一见如故，仿佛回到了学生时代。

![图片来源于网站](http://obfe8r4sl.bkt.clouddn.com/timg.jpeg)

**Comment by flclflcr** [comment]
## **04班班级信息**

 - **班级编号：04**

 - **班级名称：中来西往**

 - **班级口号：年轻不刁怎么行**

 - **级LOGO：![此处输入图片的描述][1]**

 - **LOGO含义：长风破浪会有时,直挂云帆济沧海**


----------
##**成员风采**
 - **成员名单：**
　

> **姓名【许敏】，昵称【风起】，来自【云南】，职务【班长】，【直播课程、毕业设计周、内容营销理论与实战、产品设计课代表】
 喜欢运动健身，打游戏，看书。希望通过努力，能和大家打成一片，成为学习中的好伙伴！**
 
　　
> **姓名【胡亚光】，昵称【兀小】来自【安徽】，职务【微信高级排版课代表】
工作已有五年，如今在做自家产品生意。很开心和大家一起学习。个人爱好足球、摄影。**  

　
> **姓名【吴剑桥】，昵称【无莫】来自【成都】，职务【启动周课代表】
研究生毕业后工作五年了，高等教育行业，负责学生新媒体中心运营，喜欢打网球听音乐会，希望跟大家度过愉快的一学期！**

　
　

> **姓名【刘娜】，昵称【小乔】来自【郑州】，职务【创意写作课代表】
毕业一年了，目前暂住郑州，在健身房上班，也是准备转行新媒体，平时喜欢看书，推理小说。很高兴认识大家，从名字开始。**

　
　

> **姓名【宗琪林】，昵称【修林】来自【枣庄】，职务【应用传播学课代表】
还没毕业，目前在枣庄实习，在一家互联网公司上班，现在带项目做公众号，平时喜欢看书，看电影，摄影。很高兴认识大家。**

　
　

> **姓名【邹楚璇】，昵称【艾米】来自【枣庄】，职务【新媒体故事结构入门课代表】
研究生毕业后在会展公司工作2年，现转行到新媒体营销，市场策划这一块，非常开心认识大家，希望在未来学习中能相互交流相互学习，共同进步哈**


----------


## **会议摘要**   

 - **2017年10月12日创建微信群，大家顺利入群**
 - **2017年10月13日进群后第一次认识到讨论，顺利选定课代表，以及班级名称和口号**
PS：希望我们04班在将来3个月的学习历程里，教学相长，有输出有输入，最终达到自己所期待的目标！
  [1]: http://webxmt.image.alimmdn.com/img/7221856487599190627.png

**Comment by flclflcr** [comment]
## **04班班级信息**

 - **班级编号：04**

 - **班级名称：中来西往**

 - **班级口号：年轻不刁怎么行**

 - **级LOGO：![此处输入图片的描述][1]**

 - **LOGO含义：长风破浪会有时,直挂云帆济沧海**


----------
## **成员风采**
 - **成员名单：**
　

> **姓名【许敏】，昵称【风起】，来自【云南】，职务【班长】，【直播课程、毕业设计周、内容营销理论与实战、产品设计课代表】
 喜欢运动健身，打游戏，看书。希望通过努力，能和大家打成一片，成为学习中的好伙伴！**
 
　　
> **姓名【胡亚光】，昵称【兀小】来自【安徽】，职务【微信高级排版课代表】
工作已有五年，如今在做自家产品生意。很开心和大家一起学习。个人爱好足球、摄影。**  

　
> **姓名【吴剑桥】，昵称【无莫】来自【成都】，职务【启动周课代表】
研究生毕业后工作五年了，高等教育行业，负责学生新媒体中心运营，喜欢打网球听音乐会，希望跟大家度过愉快的一学期！**

　
　

> **姓名【刘娜】，昵称【小乔】来自【郑州】，职务【创意写作课代表】
毕业一年了，目前暂住郑州，在健身房上班，也是准备转行新媒体，平时喜欢看书，推理小说。很高兴认识大家，从名字开始。**

　
　

> **姓名【宗琪林】，昵称【修林】来自【枣庄】，职务【应用传播学课代表】
还没毕业，目前在枣庄实习，在一家互联网公司上班，现在带项目做公众号，平时喜欢看书，看电影，摄影。很高兴认识大家。**

　
　

> **姓名【邹楚璇】，昵称【艾米】来自【枣庄】，职务【新媒体故事结构入门课代表】
研究生毕业后在会展公司工作2年，现转行到新媒体营销，市场策划这一块，非常开心认识大家，希望在未来学习中能相互交流相互学习，共同进步哈**


----------


## **会议摘要**   

 - **2017年10月12日创建微信群，大家顺利入群**
 - **2017年10月13日进群后第一次认识到讨论，顺利选定课代表，以及班级名称和口号**
PS：希望我们04班在将来3个月的学习历程里，教学相长，有输出有输入，最终达到自己所期待的目标！
  [1]: http://webxmt.image.alimmdn.com/img/7221856487599190627.png

**Comment by flclflcr** [comment]
## **04班班级信息**

 - **班级编号：04**

 - **班级名称：中来西往**

 - **班级口号：年轻不刁怎么行**

 - **级LOGO：![此处输入图片的描述][1]**

 - **LOGO含义：长风破浪会有时,直挂云帆济沧海**


----------
## **成员风采**
 - **成员名单：**
　

> **姓名【许敏】，昵称【风起】，来自【云南】，职务【班长】，【直播课程、毕业设计周、内容营销理论与实战、产品设计课代表】
 喜欢运动健身，打游戏，看书。希望通过努力，能和大家打成一片，成为学习中的好伙伴！**
 
　　
> **姓名【胡亚光】，昵称【兀小】来自【安徽】，职务【微信高级排版课代表】
工作已有五年，如今在做自家产品生意。很开心和大家一起学习。个人爱好足球、摄影。**  

　
> **姓名【吴剑桥】，昵称【无莫】来自【成都】，职务【启动周课代表】
研究生毕业后工作五年了，高等教育行业，负责学生新媒体中心运营，喜欢打网球听音乐会，希望跟大家度过愉快的一学期！**

　
　

> **姓名【刘娜】，昵称【小乔】来自【郑州】，职务【创意写作课代表】
毕业一年了，目前暂住郑州，在健身房上班，也是准备转行新媒体，平时喜欢看书，推理小说。很高兴认识大家，从名字开始。**

　
　

> **姓名【宗琪林】，昵称【修林】来自【枣庄】，职务【应用传播学课代表】
还没毕业，目前在枣庄实习，在一家互联网公司上班，现在带项目做公众号，平时喜欢看书，看电影，摄影。很高兴认识大家。**

　
　

> **姓名【邹楚璇】，昵称【艾米】来自【枣庄】，职务【新媒体故事结构入门课代表】
研究生毕业后在会展公司工作2年，现转行到新媒体营销，市场策划这一块，非常开心认识大家，希望在未来学习中能相互交流相互学习，共同进步哈**


----------


## **会议摘要**   

 - **2017年10月12日创建微信群，大家顺利入群**
 - **2017年10月13日进群后第一次认识到讨论，顺利选定课代表，以及班级名称和口号**
PS：希望我们04班在将来3个月的学习历程里，教学相长，有输出有输入，最终达到自己所期待的目标！
  


  [1]: http://webxmt.image.alimmdn.com/img/7221856487599190627.png

**Comment by ManYueView** [comment]
# 班级介绍

编号：01
班级名称：七匠
班级口号：匠心的人，酱紫的新媒体！
班级logo：（稍后上传）

# 成员风采

姓名：温月 昵称：蛋黄酱  from北京
职务：班长   职业：学生
爱好：读书，桌游，旅行
个人介绍：just do it ！

姓名：冯长乐  昵称：鱼子酱  from北京
职务：内容营销理论与实战课代表  职业：服装定制店店主
爱好：钓鱼，读书，户外活动
个人介绍：相信永远有机会让生活变的更好！

姓名：杨雷  昵称：芥末酱  from北京
职务：新媒体应用传播学课代表  职业：市场
爱好：户外、小说
个人介绍：跟芥末酱一样，伪小清新，且呛。

姓名：黄斌   昵称：川香酱  from北京
职务：故事结构课代表  职业：建筑结构工程师
爱好：旅游 拍照 读书
个人介绍：热爱生活，努力让每一个明天都成为更好的今天。

姓名：程雯  昵称：甜辣酱  from北京
职务：新媒体产品定位课代表  职业：农业技术员
爱好：养花，追剧，宅
个人介绍：满口东北大碴子味儿的南方girl

姓名：黄鑫 昵称：   from北京

姓名：庄宝玉 昵称：山楂酱 from北京
职务：高级排版课代表   职业：数据分析
爱好：旅行，手工
个人介绍：我是幸运的，更是幸福的，努力每一天！

————————————————————————————————————————————
PS：有些需要补充的在后续添加！

会议记录：2017.10.15上午十点半一起语音聊天，互作介绍~确立课代表，班级名称及口号。

**Comment by ManYueView** [comment]
# 班级介绍

编号：01
班级名称：七匠
班级口号：匠心的人，酱紫的新媒体！
班级logo：

# 成员风采

姓名：温月 **昵称：蛋黄酱**  from北京，
职务：班长   职业：学生
爱好：读书，桌游，旅行
个人介绍：just do it ！

姓名：冯长乐  **昵称：鱼子酱**  from北京
职务：内容营销理论与实战课代表  职业：服装定制店店主
爱好：钓鱼，读书，户外活动
个人介绍：相信永远有机会让生活变的更好！

姓名：杨雷  **昵称：芥末酱**  from北京
职务：新媒体应用传播学课代表  职业：市场
爱好：户外、小说
个人介绍：跟芥末酱一样，伪小清新，且呛。

姓名：黄斌   昵称：川香酱  from北京
职务：故事结构课代表  职业：建筑结构工程师
爱好：旅游 拍照 读书
个人介绍：热爱生活，努力让每一个明天都成为更好的今天。

姓名：程雯  **昵称：甜辣酱**  from北京
职务：新媒体产品定位课代表  职业：农业技术员
爱好：养花，追剧，宅
个人介绍：满口东北大碴子味儿的南方girl

姓名：黄鑫 **昵称：千叶酱** from北京
职务：创意写作课代表 职业：编辑
爱好：摄影 
个人介绍：没什么愿望，赚钱就行。


姓名：庄宝玉  **昵称：山楂酱** from北京
职务：高级排版课代表   职业：数据分析
爱好：旅行，手工
个人介绍：我是幸运的，更是幸福的，努力每一天！
————————————————————————————————————————————
PS：有些需要补充的在后续添加！

**会议记录：2017.10.15上午十点半一起语音聊天，互作介绍~确立课代表，班级名称及口号。**

**Comment by ManYueView** [comment]
# 班级介绍

编号：01
班级名称：七匠
班级口号：匠心的人，酱紫的新媒体！
班级logo：(后续添加）
# 成员风采

姓名：温月 **昵称：蛋黄酱** from北京，
职务：班长 职业：学生
爱好：读书，桌游，旅行
个人介绍：just do it ！

姓名：冯长乐 **昵称：鱼子酱** from北京
职务：内容营销理论与实战课代表 职业：服装定制店店主
爱好：钓鱼，读书，户外活动
个人介绍：相信永远有机会让生活变的更好！

姓名：杨雷 **昵称：芥末酱** from北京
职务：新媒体应用传播学课代表 职业：市场
爱好：户外、小说
个人介绍：跟芥末酱一样，伪小清新，且呛。

姓名：黄斌 **昵称：川香酱** from北京
职务：故事结构课代表 职业：建筑结构工程师
爱好：旅游 拍照 读书
个人介绍：热爱生活，努力让每一个明天都成为更好的今天。

姓名：程雯 **昵称：甜辣酱** from北京
职务：新媒体产品定位课代表 职业：农业技术员
爱好：养花，追剧，宅
个人介绍：满口东北大碴子味儿的南方girl

姓名：黄鑫 **昵称：千叶酱** from北京
职务：创意写作课代表 职业：编辑
爱好：摄影
个人介绍：没什么愿望，赚钱就行。

姓名：庄宝玉 **昵称：山楂酱** from北京
职务：高级排版课代表 职业：数据分析
爱好：旅行，手工
个人介绍：我是幸运的，更是幸福的，努力每一天！
————————————————————————————————————————————
PS：有些需要补充的在后续添加！

**会议记录：2017.10.15上午十点半一起语音聊天，互作介绍~确立课代表，班级名称及口号。**

**Comment by 2287510467** [comment]
# 班级介绍：
·编号：06
·班级名称：奥特曼小怪兽终极六班
·班级口号：光与暗，在于地平线；我与你，才是终极点！
·班级logo：
![657360132728489753](https://user-images.githubusercontent.com/9007751/31584560-3e1556dc-b1e3-11e7-83be-bd2eaa808789.jpg)

·含义：真正的对手那里有无穷的勇气向你涌来，终极的目的是握紧彼此、永不放弃！
# 成员介绍：
姓名【陈林伟】，昵称【叶七里】，来自【山西】，职务【班长】，担任课代表【直播课程、毕业设计周、微信高级排版课代表】目前是奔赴在职业摄影师道路上的数字媒体技术专业的大二学生，是个什么都想了解，哪里都想去的小家伙。

姓名【李可】，昵称【李可】，来自【安徽】，职务【学渣】，担任课代表【内容营销理论与实战】
，目前是个新媒体小白，在新媒体的路上慢慢摸索。

姓名【樊紫薇】，昵称【Vicky】，来自【杭州】担任【新媒体产品定位】课代表，大三学生，电子信息工程专业，喜欢尝试不同领域的东西激发更多的热情，希望和大家共同努力，完成自己的目标！

姓名【吴珏】，昵称【PENNY-UP】，来自【浙江】，职务【故事结构课代表】，从事【教育行业】
喜欢学习新事物，探索新知识，平常最爱做的是旅行，拍照，希望在这段时间和大家一起学习，一起加油，增加新技能.

姓名【蒋超群】，昵称【疯不狂】。担任课代表【新媒体创意写作】。来自【湖南】。当前职业【物流管理】。自我介绍：阳光是我，认真是我，痴迷书籍是我，满怀信念依旧是我。

姓名【张静】，昵称【卡夫卡有点卡】，来自【杭州】担任【新媒体应用传播学课代表】，毕业两年，传播学专业，目前供职于传统媒体，希望转型新媒体。喜欢看书，电影，希望和大家一起度过愉快的三个月。一起加油！


![img_20171015_195250](https://user-images.githubusercontent.com/9007751/31584552-0a147002-b1e3-11e7-8c51-be5db0676e02.jpg)


## 会议摘要：
2017年10月14日大家进行了第一次小会，确定了班级名称与口号，在大家的互助下完成了logo设计，并确定了各科课代表。

**Comment by xiezeyuan** [comment]
班级介绍

编号：02
班级名称：藏锋组
班级口号：天行健，君子以自强不息！
班级logo：



成员风采
姓名：谢江华 昵称：谢泽远 from深圳
职务：班长 职业：运营
个人介绍：厚积薄发！

姓名：陈基广 昵称：阿基 from深圳
职务：内容营销理论与实战课代表 职业：渠道运营
个人介绍：工作3年了，想要提高自己的输出能力，尝试新的突破，性格慢热，热了之后就骚(^_^)a

姓名：梁德润 昵称：Darren from广州
职务：创意写作课代表 职业：运营
个人介绍：跟芥末酱一样，伪小清新，且呛。

姓名：伍嘉诚 昵称：江小鱼 from中山
职务：微信高级排版课代表 职业：工程造价员
个人介绍：江中小鱼，以梦为马。

姓名：杨欣鸿 昵称：泥磕杨 from揭阳
职务：新媒体产品定位课代表 职业：大学生
个人介绍：一名在实习的大学生，出于对新媒体的兴趣，希望可以转行从事新媒体。

姓名：气筒 昵称：咚咚 from深圳
职务：应用传播学课代表 职业：学生
个人介绍：目前是一名学生，性格开朗，熟悉了之后的我会更加热情（hua lao）。希望能从事媒体类工作，正在努力学习中，请大家多多指教。

姓名：谭棋议 昵称：棋议  from澳门
职务：故事结构课代表 职业：大学生
个人介绍：我今年在新浪微博实习，就职于短视频运营部。我个人很放的开，无论是谈论BOY  Next  door，五黑，还是坐下来讨论STP,4PS。。。

————————————————————————————————————————————

会议记录：
2017.10.13投票确定班级名称及口号。
2017.10.14确定班级logo。
2017.10.15 完成课代表选举。

**Comment by gonglingyou** [comment]
# **我们的小家：**

班级编号：08

班级名称：00到∞

班级口号：坚持不懈，创意无限

班级logo：
![webwxgetmsgimg](https://user-images.githubusercontent.com/32874472/31671756-4e2a53b4-b38d-11e7-8e3d-cc46d719dd87.jpg)


含义：在黑色的未知世界里，以新媒体为探索事物的慧眼，创造属于我们无止尽的未来！

# 我们的风采

## 一堆小伙伴们是谁？

我叫卢艳霞，昵称：箐吟，市场推广，深圳，新媒体应用传播课代表，相信上进青年是有前途的

我叫熊律，昵称：律公子，故事结构课代表，来自广州，运营，平凡而不平庸的美少女战士

我叫张皓，昵称：子羽灏，东北银，硕士毕业后首次南下到深圳工作，现做产品策划。产品定位的课代表，我的目标是:好好工作，好好做人，成为一名全栈产品经理

我叫钟海兴，昵称：kong1437，创意写作课代表，来自广东湛江，造价员。相信知识改变命运，每天成长一点点，耐心通向财富自由之路。

我叫桂丽媛，昵称：诸葛略懂，常州，行政，微信终极排版课代表，生活中的好姑娘，思想上的女流氓，外形上的柔情少女，心理上的变形金刚

我叫余丽，昵称：青春不单行，现在江苏，大四学生，内容营销理论与实践课代表，不必仰望别人，自己亦是风景

我叫龚羚友，昵称：圆木桶，小班班长，来自深圳，从事大客户销售，阳光、开朗、爱运动，爱阅读，有点文字控，还有一点点小帅，但这点帅没什么用，因为从来战胜不了女生的矜持

## 小伙伴的风采：

真是帅哥、女神、学霸、绅士的集中营！连我们都不得不佩服我们自己，哈哈！
![webwxgetmsgimg 1](https://user-images.githubusercontent.com/32874472/31671770-54426a7a-b38d-11e7-94d4-7377f66dfc05.jpg)

## 会议纪要
2017年10月14号完成班级贴汇总和课代表分配

**Comment by Sophie919** [comment]
# 03班介绍

### *班级编号：03

### *班级名称：跃站人

### *班级口号：越学习，跃创意

### *班级logo：（如下图）

### logo含义

人生的每一个下一站都充满了惊喜与挑战，跨越它不仅需要勇气，更重要的是持之以恒的信念，跳出既定思维，看别样风景——新媒体，我们来啦！

### logo设计解释

橙色跳跃的小人取自“跃”字的“足”字旁字形，站字下面的“口”以橙色突出显示，寓意站台。橙色代表活力，蓝色代表思考，蓝橙相撞，激发出创意的火花。
![615973471](https://user-images.githubusercontent.com/32765756/31673252-58be4908-b391-11e7-93b4-50cd8d8b80aa.jpg)

# 成员风采
## 风采录

姓名 | 昵称 | 担任职务 | 地点 | 职业 | 兴趣爱好
-- | -- | -- | -- | -- | --
戴敏捷 | 九玉子 | 班长，任启动周，直播，毕业设计，内容营销理论与实战课代表 | 天津 | 运营 | 动漫/影视/旅游/读书
张逾 | yufeiyu800701 | 新媒体传播学课代表 | 上海 | 行政 | 美食/新媒体
锁佳 | 美错 | 新媒体故事结构入门 | 天津 | 待业 | 唱歌
陈琪 | 啾啾mooc1451876355130 | 新媒体产品设计 | 上海 | 产品 | 看书/独处/电影/画展
葛梦丹 | MadeleineGMD | 新媒体创意写作 | 上海 | 餐饮业行政 | 唱歌/跳舞/画画/美食（正在努力减肥）
陈昊 | 159328404 | 微信终极排版 | 上海 | 产品 | 打游戏/健身/打篮球/吃好吃的（努力脱离死肥宅）

## 风采展示
哈哈，80，90齐聚一堂，不论年龄，因共同的目标我们聚在一起，我们是爱学习，爱生活，寻找人生旅途创意的跃站人！
![2068145730](https://user-images.githubusercontent.com/32765756/31673658-5ef46c16-b392-11e7-801e-15f512b38f56.jpg)

### 会议时刻

*10月16日确定了班级名称，口号和logo

*10月17日logo制作完成，谢谢我们的设计师哦~

*相聚学习，加油fighting！

**Comment by hibining** [comment]
09班
# 班级名称：未知数
#### 班级口号：挑战自我 潜能无限
#### 班级LOGO：![Markdown](http://i4.bvimg.com/615174/91d0f8f0df2b8db4s.jpg)
-----
## 成员介绍：
姓 名|昵 称|课代|地区|职业|宣言
---|---|---|---|---|---
李碧凝|团嗞| 全栈新媒体启动/直播课程/毕业设计周| 印度|学生|为什么不试试
王妍|青青青漓| 新媒体应用传播学|浙江温州|学生|麋鹿兴于左而目不瞬
李跃|跃跃|故事结构|宜宾|团市委宣传人员|抓住青春不放手~
杨昊雨|HOPEily|内容营销理论与实战| 四川遂宁|学生|自律给我自由
张瑞俊|椅子山呱呱蛙|微信排版|上海|学生|大吉大利晚上吃鸡
蒋紫璇|蓝鲤|新媒体产品定位| 深圳| 文案|在年轻的时候，做想做的事！
夏雪吟|夏amo|新媒体创意写作|湖北武汉|市场|人生贵知心，定交无暮早
---

- 10月13日 小伙伴们第一次线上聚会，确定了班级名称口号和logo，感谢@王妍的点子~
- 10月17日 @李跃同学logo制作完成，感谢~
- 10月18日 迎来三位新伙伴。
- 未来的日子一起闯！

---

**Comment by amiaojun** [comment]
**班级编号**   07

**班级名称**  八俊

**班级口号**  做新时代的八俊才子

**班级logo**
![image](https://user-images.githubusercontent.com/32951099/31808297-19873194-b5a5-11e7-987b-168aa58b40e3.png)


Logo含义  “八俊”一词出自《后汉书·周举传》称同一时代有才望的八人，我们八人团队以此为目标努力，成为新时代的八俊才子。

**成员介绍：**

- 姓名：曹逊
昵称：  喵喵
职务：  班长
城市：  山东潍坊
职业：  待业
个人介绍：未知的一切充满好奇与恐惧。

- 姓名：杨斌 
昵称：一匠到底  
职务：新媒体产品定位课代表
城市：北京 
职业：定制家具经销商
个人介绍：千里之行，始于足下！借助新媒体实现华丽转身，努力ing！

- 姓名：马克
昵称：可可
来自：青岛
职务：新媒体故事结构入门课代表
职业：记者
个人介绍：供职于纸媒，以码字为生。17年除了当了妈妈还成功沦为了公号狗。都说一孕傻三年，我生了孩子好像顺带把脑子也生出来了，急需充电。

- 姓名：许箐月
昵称：路过的丫头
职务：新媒体应用传播学
职业：待业
来自：宁夏
个人介绍：人蠢话还多脑残90后，为了新的工作在拼命努力中

- 姓名：徐雯蕴
昵称：徐仙后儿
职务：新媒体创意写作
职业：it
来自：北京
个人介绍：人设一点也不饱满，显得特别猪的加班狗

- 姓名：daniel 
昵称：daniel 
职务：微信高级排版
职业：服装批发 自由撰稿人
来自：辽宁
个人介绍：你好

- 姓名：黄健
昵称：天行健
职务：内容营销理论与实战
城市：北京
职业：艺术设计
个人介绍：视觉的思考与践行，书法研习、品牌规划设计，近期对美食产生兴趣

- 姓名：郎强
昵称：  永临
城市：北京
职业：编辑
个人介绍：古籍图书编辑，今后会做知识付费的课程会运到微信号的运营，所以来学习

————————————————————————————————————————————
**会议记录**

- 10月12日建立班级小群

- 10月19日班级成员到齐

- 10月20日确定班级名称和logo

- 共同学习，共同进步

**Comment by tujiu-026** [comment]
### 05班级介绍
---------------
* **班级编号**  ：05
* **班级名称**  ：十万+
*  **口号**  ： 篇篇十万加，个个顶呱呱
*  **log含义**   :十万,数字是  100000 ,1、5个零代表我们5班    2、5个零代表我们分别来自5个地方（辽宁  河北  湖南   贵州   福建）3、1 作为5个0串一起的轴   代表我们一个整体的力量 ！  
* **log**   ：
![Alt text](./log.png)

--------------------------------------------------------
###  成员风采
* 姓名：吴华明    
* 昵称： 秃鹫
* 来自：福建 
* 担任职务：班长，启动周、直播课程、毕业设计周课代表
*  职业：之前从事外卖平台中层管理和营销，现在待业 。
*  个人宣言：通过这次新媒体运营的学习提高自己的能力、开拓视野
   
   -----------------
   
*  姓名：潘高翔 
*  昵称：潘高翔
*  来自：湖南
*  担任职务：新媒体产品定位课代表
*  职业：从事体育互联网行业、产品
*  个人介绍：掌握新媒体知识的体系，熟悉各个渠道的特点，了解粉丝经营的要点。

-------------
*  姓名：叶益役
*  昵称：认真一夏
*  来自：贵州
*  担任职务：内容营销理论与实战课代表 
*  职业：快递  之前在上海从事电话销售售卖搜索引擎推广位 读过网络营销
*  个人介绍：学习这门课主要是找份这样的工作，还有之前干的是销售，说是要干好销售就先干好运营，所以就来了，也是喜欢多种都会。
　　
   -----------------

*  姓名：林赟 
*  昵称： Noah Lin 
*  来自：福建 
*  担任职务： 故事结构课代表 
*  职业：从事骑行类互联网、软件产品 
*  个人介绍：想比较系统的了解新媒体的知识体系和基本方法论，主要计划还是通过听课、交流、实践，寻找一些可能的切入点，掌握新媒体操作的基本方法和规律。

   -----------------

*  姓名：常新 
*  昵称：  Hsin 
*  来自：辽宁  
*  担任职务：新媒体应用传播学课代表
*  职业：地产行业
*  个人介绍：学习课程是打算运营公众号吸粉儿，学习新媒体营销技巧。多多关照，共同进步。
　　
   -----------------

*  姓名：朱文超 
*  昵称：猪 几
*  来自：湖南
*   担任职务：新媒体创意写作课代表
*  职业：从事新媒体公司 |
*  个人介绍：
　　　
   -----------------
 
*  姓名： 陈冲宇
*  昵称：馍馍
*  来自：河北
*  担任职务：微信高级排版课代表
*  职业：学生
*  个人介绍：新媒体是时代的步伐，是另一番天地，怎么也要去开拓一番，因为看起来挺有意思。从我所学专业角>度来看，我不一定从事有关新媒体的工作；但是，这并不影响我学习新媒体的热情。还是那句话，看起来挺有意思，不如我就试一试。
