### ISSUE TITLE
自我介绍

### ISSUE THREAD

**Issue by bzlx1213** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#88]
#86 自我介绍
  哈喽，大家好，我叫刘娜，你也可以叫我**小乔**，历史课上学过的周瑜的妻子也叫小乔这样会不会更好记呢？

  我的家在江苏徐州，哪里有著名的沛县狗肉，不过我不提倡吃这个，狗是人类最好的朋友对吧。我目前暂时居住在郑州，刚毕业大学是在这边上的，不过年后可能会去杭州发展。

   2016年九月加入 [简书](http://www.jianshu.com/u/6c8b54aa92fel)，2017年10月13在上面发表了我的第一篇文章，我最近在练习写作，如果大家感兴趣的话也可以关注我一下。

###  我是谁？从哪里来？要到那里去？

  这个问题好深奥一下子就把我问住了。**我希望我不是我的名字，不是我的工作，不是为我所拥有的任何头衔，而是当我没有工作，忘记名字，我依然可以走在自己所坚持的路上，不会迷失。**

### 为什么加入半撇私塾？
  今年六月份我在网易上找做公众号的教程时发现了半撇私塾的微专业，当时也是比较迷茫吧，大学刚毕业，要什么专业技能都没有，看到这个课程就很想报名，又有些犹豫，直到今年九月份我看到了怀左的一篇文章，大学毕业后有多少人活成了廉价劳动力，我希望我不是，所以就毅然决然的报名了，希望学习过后能发现一个不一样的自己。

### 最擅长的一项技能?
   两年前在毛戈平化妆学校学过半年的化妆，也在影楼工作过一段时间，对时尚有自己的理解，化妆基础还可以，就是发型基础很差，可能是因为自己一直是短头发对这个比较生疏。

### 未来的输出计划？

- 参加了简书里面无戒老师的365计划，所以每周要更新五篇文章

- 做好属于我自己的公众号

- 成为简书签约作家

### 推荐利器

  我就推荐一款书信交友的软件吧**过客**一款写信交友的软件。在这个互联网高速发达的时代，即时通讯工具越来越多，可能你已经忘记了以前写书信等书信时的乐趣，这款应用可以让你结交到志同道合的朋友还可以找到你寻找的远方。

不擅长自我介绍，就这么多吧。记得我叫小乔，铜雀春深都没能锁住的小乔。

**Comment by fang-yu** [comment]
微专业需要在https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/85 跟帖报告，回复错地方了，我先关闭这一条issue。
