### ISSUE TITLE
适合在夏天看的电影

### ISSUE THREAD

**Issue by xiaoxianger** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#89]
[青木瓜之味](https://www.youtube.com/watch?v=-WRI6SKtKbM)
忘了在哪里被安利的，被封面吸引就去找来看了。画面很清新。
片子的BGM很有意思，刚开始的时候会觉得有点诡异，还好不是晚上看的。有鼓点、蛙叫、和不知名的类似琵琶的乐器弹奏的声音。很多声音会配合着画面由远及近
片中浓浓的热带气息让人想象不到这是越南的导演在法国搭棚拍摄的。
很多画面都可以截图下来当屏保，很多细节会触动到内心，但是说不出什么感觉。
但是故事的内容不是很喜欢……有种重蹈覆辙的感觉。

**Comment by fang-yu** [comment]
犯错地方啦，作业是跟帖回复，我先关闭这一条issue。
