### ISSUE TITLE
这里是柚子呀

### ISSUE THREAD

**Issue by youziya** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#90]
# 1.基本情况
## 名号：柚子呀
*关于名号这个事，不同平台几乎都不同，试过各种水果，但最终还是抵不过对微苦的柚子的爱~*
## 坐标：北京
*虽身在帝都，却无需体会地铁的早晚高峰，因为北京还有个距离城区好几十公里的密云县，山清水秀，人杰地灵，密云水库，水库活鱼~~ ……*
## 生命故事……
看到这个标题有些忐忑，毕竟二十多年来从不曾觉得自己是个有故事的人，索性就从这几个基础问题来吧
### 你是谁
我叫程雯，说到这个名字也实在随意的很，因为小学一年级和班级同学同名，于是被老师赐名，以至于开学一个星期都不记得自己叫什么……
很多时候，都觉得自己真的是普通的过分，特别是在想自我介绍的时候尤为明显，没有什么特点，平凡到感觉拿不出手，但是这又怎么样呢，我依旧是那个独一无二的我，是来到网易微专业想要成长的柚子呀
### 从哪里来，到哪里去
>从一个迷茫的过去来，想要去找到一个方向开始新的生活

大学毕业后就到了一个专业相关的小公司过上了悠哉的生活，越来越习惯则安逸又荒废的节奏，却也害怕就这么习惯着走不出来
会有那么恍然一瞬间惊醒，想要从这种氛围里跳脱出来，总要去追求点什么，然后，接触到了运营
### 为什么参加半撇私塾
对半撇私塾有印象，应该是一次偶然的机会看到了半撇老师的课，那轻松又自信的侃侃而谈是我最初关注半撇私塾的原因，当然，最后报了课程还是为了很现实的目标，积累技能，然后转行换工作，哈哈哈哈:satisfied::satisfied::satisfied:
# 2.技能介绍
这个真的是很难过啊，因为并没有什么过硬的技能拿的出手，如果小学美术、初中数学、高中作文、扫雷、数独也可以算的话……或许……（:joy: :joy: :joy:）
- [x] Office用的一般
- [x] Ps只会一点点
- [x] 写东西能读懂
- [x] 字写的还可以
- [x] 好像没了……
# 3.输出计划
- 每周在公众号上推文至少一篇
- 每两周在简书上输出学习笔记至少一篇
- 每周整理本周学习笔记思维导图，并作总结
# 4.利器推荐

**滴答清单**
![image](https://user-images.githubusercontent.com/32917343/31800481-cf1a5ebe-b573-11e7-9ff6-497b7cff8b29.png)
对于我这种想到一件事马上就能忘的人，真的非常需要快速记录和设置提醒，滴答清单的功能不是特别多，不像朝夕日历那样功能强大，自我感觉他最棒的点在于语音输入时的自动提取时间并设置提醒，可以说是很贴心了

**Snapseed 和 VSCO**

![image](https://user-images.githubusercontent.com/32917343/31800497-e79c3980-b573-11e7-8fde-77a2d17a6632.png)
这是我手机里常驻的修图软件，VSCO里的滤镜真的是超级棒啊，snapseed 我一般是用来调整图片，功能很多，操作也简单，容易上手

**Comment by fang-yu** [comment]
自我介绍跟帖回复即可，不需要单独新开帖子，我先关闭这一条issue了。
