### ISSUE TITLE
【微专业第二期】学员报到：一起探索全栈新媒体人的世界！

### ISSUE THREAD

**Issue by Lassung** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#92]
# **基本情况**
- **名号**：卢艳霞
 - **坐标**：深圳
- **简书个人主页链接：**[简书主页](http://www.jianshu.com/users/bcaac100060e/timeline)
- **生命故事**：现在就职与于公司市场部，带领团队成员做策划做品牌推广，在这个知识快速更迭的时代，个人需要不断学习新知识。
- **为什么参加半撇私塾**：学习新媒体知识，拓宽视野
# **技能介绍**
PPT、Excel，现在可以快速做出美观的PPT、Excel表格处理快速有序了很多，是因为学习了秋叶的课程
# **输出计划**
- 未来在平台上每天输出两篇文章，前面2个月阅读量实现500
- 坚持每天读推广相关文章、读书，做笔记，提升文感拓充文库，并分析作者思路，启发退广思维
# **利器推荐**
## **得到app**
上班的路上或一个人散步运动的时候听一段逻辑思维，听听别人对一些现象、故事、
热点的思考
## **VIVA畅读**
一直喜欢读杂志，这里可以下载免费的杂志看，文章也很有品质，喧嚣混杂内容世界的清流
## **UC名家**
名家对当下社会热点的深度解读
## **印象笔记**
类似于收藏夹，一键管理想要收藏保存的内容

**Comment by banpie** [comment]
报道在这里回帖哈：https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/85
