### ISSUE TITLE
嗨，我是桂丽媛，你们好哇！

### ISSUE THREAD

**Issue by losewinggly** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#95]
# 嗨，我是桂丽媛，你们好哇
## 基本情况
-  名号：诸葛略懂   ~~不是诸葛所以就略懂略懂~~
-  坐标：常州
-  简书：[欢迎互粉](http://www.jianshu.com/users/e169d2d4f0f9/timeline)

-  生命故事：
1.  我是桂丽媛，现居江苏常州，一个生活安逸的90后女生。毕业后帮衬父母，在家从事行政管理工作。
2. 我:生活中的好姑娘，思想上的女流氓，外形上的柔情少女，心理上的变形金刚。
3. 为什么而来：不努力可是要轮去相亲的，这是我目前纠结的现状。在被七大姑八大姨游说相亲多次后，我认为我能沦落至此，主要是因为我一直没能做到真正的独立。打铁还需自身硬，只有我优秀了，我才能对他们所谓的剩女观念予以反驳，也才能够对很多事情说不。这次参加半撇训练营，是希望认识更多积极的小伙伴，更新思维，不断学习掌握新媒体知识，提高能力。换句话说就是要能够有挣钱的能力，做到经济独立。
****
## 技能介绍
了解网页后台排版和维护，之前自建了网站并且参与了后期维护，主要是在网上自学，加实操。
***
## 输出计划
 前一个月学习补充武装头脑，后期再输出，争取在简书每月有3-4份心得更新
***
##  利器推荐
网易云音乐，是我觉得最好的音乐软件。每日会根据个人喜好推送音乐，而且评论栏里你能发现很多人的故事，是我最喜欢的放松利器。
***

**Comment by fang-yu** [comment]
微专业学员报到在这里地方跟帖完成哈：https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/92 ，我先关闭这一个帖子。
