### ISSUE TITLE
试试markdown

### ISSUE THREAD

**Issue by shendengnian** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#97]
# 半撇私塾的第一天

![banpie logo](http://or98sir3g.bkt.clouddn.com/bala01.jpg)

哈喽大家好! 姑且叫我 **一只想学运营的码农**吧，半撇私塾是我在知乎上了解到的，没过多久决定报了尊享版，因为我相信在接下来的两个月回报远不是这几千块所能度量的，所以心里丝毫没有花钱的肉痛感，对孤来讲，**花钱开阔自己的知识面都不算花钱** 23333.

今天先简单做个总结小分享，文笔一直是硬伤，显的上文不接下文的这也是我想学运营的原因之一，还能提升自己的文笔。

## 神马是运营

通过这两天的了解，原来运营要是细分竟然还分了很多类，内容运营、用户运营、活动运营、新媒体运营、文案、数据运营、产品运营balabala

**Comment by fang-yu** [comment]
Markdown 练习场在https://github.com/BPteach/Full-Stack-New-Media-Hacker-Bootcamp/issues/8 跟帖完成哈，我先关闭这一条issue。

**Comment by shendengnian** [comment]
早上好，好的，哈哈，我刚才也想屏蔽掉这条的

**Comment by fang-yu** [comment]
@shendengnian 如果不想要收到通知，点击右边的`unsubscribe`mute这一条就行了。
