### ISSUE TITLE
我知道你看好新媒体岗位的发展

### ISSUE THREAD

**Issue by lwxy87** [BPteach/Full-Stack-New-Media-Hacker-Bootcamp#99]
>### 你也想快速的入行
> # 可现实是

- 小公司不会培养你，也没人培养你；
- 大公司会培养你，待遇却很低廉；

> 试想，你是老板会给一个零基础的员工什么样的培训和待遇？

所以快速的掌握“新媒体”理论知识：
- 让你见到案例就可以夸夸其谈，一针见血。

**并且** 还收获一个由你个人创作的**专业**的新媒体作品集：
- 唬的住HR的作品案例！让HR看你的简历严重放光！

半撇私塾的「全栈新媒体骇客训练营」尊享版就是你的“菜”：
- 他有深入浅出的系统知识学习，和经典的作品搭建实战；
- 同时还有

> 简历修改、撰写求职信、模拟面试、薪酬谈判全程辅导

**这些全部是1v1辅导喔～**

使得真正快速、体面的零基础转行新媒体，某得一个称心的岗位。

其实我本人学的不是尊享版，而是标准版，因为我不转行只是做知识储备。
跟上时代潮流，而如果你是**“想零基础快速转行”**的人，请选择“尊享版”，一定物有所值！

>分析：
标题运用情感诉求，内容结合理性诉求，最后利用自身经验结合一点人品诉求。请大家点评！

**Comment by fang-yu** [comment]
Hi，练习场的作业需要在对应的issue跟帖回复，我先关闭这一条issue哈。
